const EXAMPLES = {
  "1": "Da, ja razuměm tebe.",
  "2": "Ne, to ne jest moja torba.",
  "3": "Čije sut one? Ne znaju. Ničije. -- Maly Princ",
  "4": "Ja ne razuměju čto ty govoriš… -- Maly Princ",
  "5": "Očevidno, postaraju se, že by moje portrety byli koliko možno věrne. -- Maly Princ",
  "6": "Ahoj, kako jesi?",
  "7": "Čao, vidimo se zautra!",
  "8": "Dobro jutro! Spala jesi dobro?",
  "9": "Dobry denj! Vhodite, prosim.",
  "10": "«Dobry večer», rěkla zmija. -- Maly Princ",
  "11": "My izhodimo. Do viděnja!",
  "12": "Ja mušu uže idti. Vidimo se!",
  "13": "Dobra noč, spi dobro.",
  "14": "Kako jesi, prijatelju?",
  "15": "Prijatny denj vam želam!",
  "16": "Dekujem — vzajemno!",
  "17": "Dekujem za pomoč.",
  "18": "Nema za čto, to jest moja dolžnost.",
  "19": "Prosim, daj mi vodu.",
  "20": "Prosim, vot tvoja karta.",
  "21": "Izvinite, kde jest toalet?",
  "22": "Žal mi je, ale nič lěpše ne iměli jesmo pod rukom. -- Titus, Romek i A'tomek",
  "23": "Dobrogo apetita, jedite!",
  "24": "Dostala je prěkrasno ime od svojego otca. -- Nehaj nas nesut...",
  "25": "Moje prězime jest Novak.",
  "26": "Nazyvam se Marek.",
  "27": "Ja jesm iz krilanskogo roda. -- Nehaj nas nesut...",
  "28": "Ale začto hočeš, že by tvoje ovce jedali male baobaby? -- Maly Princ",
  "29": "Ja htěl byh uviděti zapad solnca... -- Maly Princ",
  "30": "Želam ti mnogo ščestja.",
  "31": "Možemo govoriti na medžuslovjanskom.",
  "32": "Možem li vzeti tutu knigu?",
  "33": "Musim uže idti k domu.",
  "34": "Ostražno! Avto jede bystrо.",
  "35": "Pomoči! Ja ne uměm plavati!",
  "52": "To jest najumnějši člověk na tutoj planetě. -- Maly Princ",
  "53": "Tamtoj muž jest naš učitelj.",
  "54": "Ne! Tuta jest uže mnogo boljna. Izdělaj mi drugu. -- Maly Princ",
  "55": "Tamta kniga jest stara.",
  "56": "Tuto jest kopija ovoj rysovanky. -- Maly Princ",
  "57": "Tamto děte plače.",
  "58": "Ne jest potrěbno, že byh žil tu. -- Maly Princ",
  "59": "Moj brat žije tam, za gorami.",
  
  "60": "Kto jest toj muž?",
  "61": "Čto ty dělaš?",
  "62": "Kogo ty vidžiš tam?",
  "65": "O kom on govori?",
  "66": "S kym ty idžeš na večerju?",
  "67": "Čija jest ta kniga?",
  "68": "Kde jest najblizša apteka?",
  "69": "Kogda ty prijdeš v dom?",
  "70": "Kak ty se čuješ?",
  "71": "Začto ty plačeš?",
  "72": "Začto ty to kupil?",
  "73": "Koliko to koštuje?",
  "74": "Ktory avtobus ide do centra?",
  "75": "Ktora kniga jest najlěpša?",
  "76": "Ktoro děte jest tvoje?",
  "77": "Odkud ty jesi prijehal?",
  "78": "Dokud ty ideš?",
  "79": "Kudy musimo jehati že by ne platiti za avtostradu?",
  "80": "Odkogda ty učiš se medžuslovjansky?",
  "81": "Dokolě budete čekati?",
  
  "82": "Naše avto jest staro ale dobro.",
  "83": "Avtobus jede k stanciji.",
  "84": "Vlak bude prijedti v šestoj časině.",
  "85": "Samolet leti vysokо.",
  "86": "On jezdi na velоsipedu vsakodenno.",
  "87": "Děti vozet se na samoběžkě po parku.",
  "88": "Veliky korab plove po morju.",
  "89": "Větrilo na lodi jest bělo.",
  "90": "Veliky kamion blokuje dragu.",
  "91": "Vhod jest tam, za uglom.",
  "92": "Izhod iz budynka jest vsegda otvorjeny.",
  "93": "Vjezd v grad jest zamknuty.",
  "94": "Izjezd iz avtostrady jest blizko.",
  "95": "Ta draga vede k morju.",
  "96": "Na avtostradu možeš jehati bystro.",
  "97": "Na tom viraže budi ostražny.",
  "98": "Na tom križišču treba stati.",
  "99": "Idi ravno, ne obračaj se.",
  "100": "Vlěvo jest park, vpravo jest škola.",
  "101": "Odbočite vpravo pri crkvi.",
  "102": "Morje jest daleko od togo města.",
  "103": "Apteka jest blizko, pet minut hoda.",
  "104": "Škola jest naprotiv pošty.",
  "105": "Avtomobil potrěbuje benzin že by jehati.",
  "106": "Treba tankovati prěd dolgoju dragoju.",
  "107": "Telefon treba zarjažati každu noč.",
  "108": "Strahovanje povinno se kupiti prěd putovanjem.",
  "109": "Tvoj bagažnik jest uže polny.",
  "110": "Ne zabudi svoj bagaž v avtobusu.",
  "111": "Ja imaju svoju torbu v ruce.",
  "112": "On je spakoval kufr prěd odjezdom.",
  "113": "Ona nese veliky rukzak na hrebetu.",
  "114": "V ktorom kraju jesi urodil se?",
  "115": "Na granici treba pokazati pasporty.",
  "116": "Graničny prěhod jest otvoreny.",
  "117": "Ja čekam povratok tvoj s radostju.",
  "118": "Kupil jesm bilet na vlak.",
  "119": "Avtobus stoji na postojkě deset minut.",
  "120": "Ne zabudi tvoju vhodnu kartu.",
  "121": "Let iz Pragi do Pariža trvaje dvě časiny.",
  "122": "Aerodrom jest daleko od grada.",

  "123": "On ne odhodi od svojego pisaljnogo stola.",
  "124": "Prinesite stolku iz drugoj komnaty.",
  "125": "Na rabotě u nas každy ima kompjuter.",
  "126": "Toj displej jest črny ibo jest izključeny.",
  "127": "Naša konferencijna sala jest mala.",
  "128": "Izgubil jesm ključ od doma.",
  "129": "Podaj nam svoje gaslo do banku. Musimo prověriti tvoje personalne dane.",
  "130": "Imajemo někaky problem s logovanjem.",
  "131": "Imaš li ty dostup k tomu fajlu?",
  "132": "Naš projekt jest gotovy.",
  "133": "Ale ne tratite vrěme na tako nudno zadanje. -- Maly Princ",
  "134": "Napisal jesm o tom zapisku.",
  "135": "Termin za ten projekt jest v najblizšy petok.",
  "136": "Direktor firmy govorit na sobranju.",
  "137": "Rukovoditelj odděla pomože ti najdti vlastnu osobu do togo zadanja.",
  "138": "Načelnik prišel na rabotu rano.",
  "139": "Naš šef jest strogy ale spravědlivy.",
  "140": "Pracovnik sklada musi nositi rabotnu odědžu.",
  "141": "Naša komanda rabotaje dobro zajedno.",
  "142": "Zaplata jest na konec měseca.",
  "143": "On prosil o povyšenje zaplaty.",
  "144": "Po trěh godah ona nakonec dostala avans.",
  "145": "Ona dobila veliku premiju za poslědnju rabotu.",
  "146": "Najemny ubijca rabotaje bez dogovora.",
  "147": "Ona jest na odpusku do konca měseca.",
  "148": "Posle izvoljnjenja on iskaje novu rabotu.",
  "149": "Verbovanje novyh pracovnikov trvaje dolgo.",
  "150": "Obučenje novyh rabotnikov trvaje tri dnje.",
  "151": "Ona ima bogate izkušenje v tej oblasti.",
  "152": "Koje sut tvoje dolžnosti v toj firmě?",
  "153": "Oddaljena rabota jest menje efektivna.",
  
  "154": "Firma oglasila bankrotstvo.",
  "155": "Kompanija s ograničenoju odgovornostju",
  "156": "To veliko prědprijemstvo ima tyseče rabotnikov.",
  "157": "Uprava firmy je v Pragě.",
  "158": "Vlastnik togo doma jest bogaty.",
  "159": "Klient vsegda ima pravdu.",
  "160": "Dostavitelj bude prinesti produkty zautra.",
  "161": "Produkty sut v skladu za domom.",
  "162": "Prěstupiliste budžet o dvadeset procent.",
  "163": "Dohod firmy raste každy god.",
  "164": "Naše razhody sut prěvelike.",
  "165": "Ničto ne jest isto kromě smrti i platb. -- Benjamin Franklin",
  "166": "Ja vam procenty ješče za měsec vnesu; potrpite. -- Prěstupanje i ukaranje",
  "167": "Odkogda je načel se razvoj, odtogda takože sut prišli problemy. -- Nehaj nas nesut...",
  "168": "Kompanija zapisala rast treti kvartal podred.",
  "169": "Nedostatok dělanij reklamovyh pričinil upadok rezultatov prodaži.",
  "170": "Naš uspěh jest rezultat dobrej raboty.",
  "171": "Tuta poražka nas naučila mnogo.",
  "172": "Bez rizika nema zabavy.",
  "173": "Naša kooperacija s tamtoju firmoju jest dobra.",
  "174": "Jedinstvo buduje, nesoglasje ruinuje.",
  "175": "Imamo silnu prěgovornu poziciju. Musimo to izkoristati.",
  "176": "Imam dlja njego propoziciju, ktoru on može odkloniti. -- Krestny Otec",
  "177": "On poslal nam prědloženje.",
  "178": "Treba tvoj podpis na tom dokumentu.",
  "179": "Tuto rěšenje jest konečno [ang. final].",
  
  "180": "Sladky aromat od ovsovyh kolačev razhodi se v kuhnji. -- Nehaj nas nesut...",
  "181": "V našej kupaljnji jest velika vanna.",
  "182": "Toalet jest v koridoru.",
  "183": "Ta komnata jest mala ale světla.",
  "184": "Otvori okno, prosim, da by vošlo něčto svěžego vozduha.",
  "185": "Ukončijte prosim vhodženje i izhodženje, dveri se zatvarjajut. -- Soobčenje v metru",
  "186": "Iz našego balkona vidimo cěly grad.",
  "187": "Podloga v kuhnji jest nečista. Prinesi utirak.",
  "188": "Stěna medžu tymi komnatami jest tonka.",
  "189": "Ni čestice praha ne možno bylo najdti v cěloj kvartirě. -- Prěstupanje i ukaranje",
  "190": "Moj dom jest moja tvrdža.",
  "191": "Toj budynok ima dvadeset etaže.",
  "192": "My živemo na tretim etažu.",
  "193": "Vozmi teleskop i běži na pokryv. -- Titus, Romek i A'tomek",
  "194": "Stupeniše do gornog etaža jest kruto.",
  "195": "Idite po koridoру do konca.",
  "196": "V pivnici hranim vino.",
  "197": "Lift ne rabotaje, treba idti pěšo.",
  "198": "Naš sused jest mily stary muž.",
  "199": "Děti igrajut v sadě.",
  "200": "Najem za tu kvartiru jest vysok.",
  "201": "Mlěko jest v hladilniku.",
  "202": "Čajnik uže kipit.",
  "203": "Hlěb pečem v peči.",
  "204": "Ona grijе juhu v mikrovaljnej peči.",
  "205": "Naša kavovarka dela dobru kavu.",
  "206": "Vari juhu v tom grnci.",
  "207": "Daj mi ložicu, prosim.",
  "208": "Vzemi vidlicu s stola.",
  "209": "Nož jest ostry, budi ostražny.",
  "210": "Polož meso na talirku.",
  "211": "On pije vodu iz skljanky.",
  "212": "Ispij čaj iz čašky.",
  "213": "Soljnica jest prazna.",
  "214": "Baci smeti v koš odpadov.",
  "215": "Ona spi v maloj spaljnjě.",
  "216": "Ta poduška jest myagka.",
  "217": "Ručnik jest v kupaljnji.",
  "218": "Postelj jest široka i myagka.",
  "219": "On lеži na divanie i čita knigu.",
  "220": "Oni sědet za stolom i jedut.",
  "221": "Pralna mašina jest plna odej.",
  "222": "Gladilo stoji na stolu.",
  "223": "Mylo jest na myvalnici.",
  "224": "Ona prinimajet duš každo jutro.",
  "225": "Vanna jest polna teploj vody.",
  "226": "Upali lampu, jest temno.",
  "227": "Světlo v komnate jest jasno.",
  "228": "Prahososalnik jest v koridorě.",
  "229": "Vzemi metlu i podměti podlogu.",
  "230": "Vzemi utirak i utri stol.",
  "231": "Každy člověk potrěbuje ljubov.",
  "232": "Ten muž jest naš šef.",
  "233": "Jej muž rabotaje v banki.",
  "234": "Ta žena govori troje językov.",
  "235": "Jej žena jest lěkar.",
  "236": "To děte jest malo i krasno.",
  "237": "Dobry denj, gospodin Novak!",
  "238": "On jest uže dorastly čelověk.",
  "239": "Moj otec učit mě voziti avto.",
  "240": "Moja mati varje oběd vsako denj.",
  "241": "Jej syn uči se v školi.",
  "242": "Naša dočera poje v horě.",
  "243": "Moja baba pripovieda mi stare povesti.",
  "244": "Jej děd jest věky i modry.",
  "245": "Ta rodina žije v velikom domu.",
  "246": "Ich svatba byja prěkrasna.",
  "247": "Posle razvoda ona žije sama.",
  "248": "Smrt jest čest žitja.",
  "249": "Na pogrebu byjo mnogo ludej.",
  "250": "Toj hlapec igrae futbol na ulici.",
  "251": "Ta děvčina čita knigu v parku.",
  "252": "On jest moj najlěpši prijatelj.",
  "253": "Moja prijateljka žive u Praze.",
  "254": "Moj kolega pomože mi s rabotoj.",
  "255": "Moja kolegica govori polsky.",
  "256": "On jest moj znajemy z raboty.",
  "257": "Imamo gosta na večerju.",
  "258": "Naš heroj spasil město.",
  "259": "Strahlivec zbegne ot boja.",
  "260": "Naš protivnik jest silny.",
  "261": "On jest naš vrag v toj vojně.",
  "262": "Izdajnik byl pokarany.",
  "263": "On dela kak pravi durenj.",
  "264": "Ne budi idiot, mysliti prěd govorenjem.",
  "265": "Zločinec izběgl prěd policijeju.",
  "266": "Jesi programist, tako napravi mi kompjuter. -- Tetka",
  "267": "Inženjer projektuje novy most.",
  "268": "Lěkar govorit, čto ja jesm zdrav.",
  "269": "Medsestra pomože pacijentu.",
  "270": "Ne ljubim hoditi do zubnogo lěkara.",
  "271": "Vsi učitelje ljubet děti.",
  "272": "Policijnik pomože nam najti doragu.",
  "273": "Vojak stoji prěd vhodom.",
  "274": "Naš šofer zna vsě dragi.",
  "275": "Kelner prinesе nam jedivo.",
  "276": "Zloděj ukral moju torbu.",
  "277": "Godite se byti buhhalterom. -- Monty Python",
  "278": "Kde je kuharek šest, tam nema čto jesti.",
  "279": "Gorniki rabotajut pod zemjeju.",
  "280": "Frizer ostrigal moje vlasy krasno.",
  "281": "Sudja prěčital rěšenje.",
  "282": "Naš advokat pomagae nam.",
  "283": "Svečennik govori v crkvi.",
  "284": "Farmer ima mnogo zemlij.",
  "285": "Lovec idu v lěs rano jutro.",
  "286": "Prodavec pokazal nam novy produkt.",
  "287": "Sovětnik pomogl nam dobrym sovětom.",
  "288": "Prostitutka stoji na uglě ulicy.",
  "289": "Naš politik mnogo obečaje ale malo děla.",
  
  "290": "V lěsě živut različne životiny.",
  "291": "Ktory vid ptic jest to?",
  "292": "Lev jest veliky sosavec.",
  "293": "Ryba žive v vodě.",
  "294": "Ta ptica leti vysoko.",
  "295": "Komar jest insekt maly, ale bezpokoječi.",
  "296": "Dinozavry žili davno prěd nami.",
  "297": "Naš pes ljubi bегati po sadě.",
  "298": "Moj kot spi na divanie.",
  "299": "...v ogromnom vozu, zapregnutom ogromnym robočim konjem... -- Prěstupanje i ukaranje",
  "300": "Krava daje mlěko každy denj.",
  "301": "Myš zbegla v ugol.",
  "302": "Ščur jest veliky i sěry.",
  "303": "Lisica jest hytра i bystра.",
  "304": "Medvěd spi vsim zimoj.",
  "305": "Slon jest veliky i silny.",
  "306": "Krokodil žive v rěce.",
  "307": "Žirafa ima dolgu šeju.",
  "308": "Malpa žive v tropičeskim lěsě.",
  "309": "Tigr jest silna životina.",
  "310": "Lev jest car zvěrej.",
  "311": "Akula žive v morě.",
  "312": "Katka plove na jezeru.",
  "313": "Bely labed poje na vodě.",
  "314": "Vrabec poje každo jutro.",
  "315": "Orel leti visoko nad gorami.",
  "316": "Pingvin ne može letěti.",
  "317": "Bočan prinosit ščestje.",
  "318": "Jastreb ulovi myš.",
  "319": "Papugaj govorit čto mu rěčeš.",
  "320": "Netopyr leti noču.",
  "321": "Zmija jest opasna životina.",
  "322": "Žaba skočila v vodu.",
  "323": "Črvjak žive v zemji.",
  "324": "Slimak ide pomaly po listu.",
  "325": "Pavuk tke svoju sět.",
  "326": "Komar letěl okolo mene vsju noč.",
  "327": "Pčela dela med.",
  "328": "Osa žalila mě za ruku.",
  "329": "Krasny motylik leti od cvěta k cvětu.",
  "330": "Čas leti, ne gubite ego.",
  "331": "Každy denj učim se što novo.",
  "332": "Noč byla temna i tihaja.",
  "333": "Tydenj ima sedem dnej.",
  "334": "Prosim bilety do kontroly! Prosim, měsečny. -- Titus, Romek i A'tomek",
  "335": "Novy god jest prěkrasny praznik.",
  "336": "To bude dnes večerom v sedmu časinu i četyrideset minut! - Maly Princ",
  "337": "Čekajte ješče pet minut.",
  "338": "Za sekundu vsě se izměnilo.",
  "339": "Počekaj jedno hvilju.",
  "340": "V toj moment ja ne znam čto rěkti.",
  "341": "Rano jutro je moje ljubimo vrěme.",
  "342": "Idemo obědat na poludnje.",
  "343": "Večer smo sěděli v parku.",
  "344": "Včera ja byh bolny.",
  "345": "Zajdem se zautra.",
  "346": "Prošlost ne možeš izměniti.",
  "347": "Budučnost jest v naših rukah.",
  "348": "Časovnik na stěně stojet.",
  "349": "V mojem telefonu jest dobry kalendar.",
  "350": "Poezdy byl zapozdněly dvadset minut.",
  "351": "Ona vsegda vstaje rano.",
  "352": "Prišel jesm raněje nego ty.",
  "353": "Prědnje kupite bilety!",
  "354": "Prěd obědom treba umyti ruce.",
  "355": "Posle raboty idemo domov.",
  "356": "Ty prišel pozdno, sědi tiho.",
  "357": "Mi gotovimo pozdněje.",
  "358": "Pojem zajedno, a potom idemo domov.",
  "359": "Někogda on žil v Parizu.",
  "360": "To byjo davno, uže ne pamětam.",
  "361": "Ona nedavno zaměnila rabotu.",
  "362": "Tutčas on ne jest doma.",
  "363": "Nyně firma rastě rychlo.",
  "364": "Vlak skoro bude.",
  "365": "Podčas govoru ne otvorjajte vrata.",
  "367": "Medžuvrěmenno ona naučila se novo slovo.",
  "368": "On ješče spi.",
  "369": "Ty uže jedl?",
  "370": "On nikogda ne govorit pravdy.",
  "371": "Ona rědko hotit pomočy.",
  "372": "Poněkogda idemo v restoran.",
  "373": "Časom on zabudet vsě.",
  "374": "Ona obyčno pije čaj jutro.",
  "375": "On často hodit v park.",
  "376": "Vsegda myj ruce prěd jedivom.",
  "377": "Děte bezprěryvno plače.",
  "378": "Neustalo šumjet v glavi.",
  "379": "Pronovo smo probovati.",
  "380": "Povtori etoto slovo ponovno.",
  "381": "Začnemo nanovo od pervogo.",
  "382": "Naglo zagrěmelo i začal dožd.",
  "383": "Pišite kako toliko prideš.",
  "384": "Prihodite čim raněje možete.",
  "385": "Dokolě ty jesi tu, ja buju s tobojom.",
  "386": "Čekaj dopoka ne prijde.",
  "387": "On doprva skončil rabotu.",
  "388": "Ona doprva tutčas naučila se to.",
  "389": "Jademo snědanje zajedno vsako jutro.",
  "390": "Oběd bude gotovy za pol časiny.",
  "391": "Na večerju imamo rybu.",
  "392": "Mně nравit se svěže ovoče.",
  "393": "Jedite zeleninu, ona polezna.",
  "394": "On ne jede meso.",
  "395": "Mlěko jest v hladilniku.",
  "396": "Kupite maslo v magazini.",
  "397": "Naš syr jest velje vkusny.",
  "398": "Kava s smetanoj jest myagka.",
  "399": "Šunka v sendviči jest vkusna.",
  "400": "Kura jest moje ljubimo jedivo.",
  "401": "Kartofelje varila jsem za oběd.",
  "402": "Děti ljubet pomfritky.",
  "403": "Ona kupi makarony v magazini.",
  "404": "Ryž se kuha dvadset minut.",
  "405": "Na snědanje jadeva kašu.",
  "406": "Salata jest svěža i krasna.",
  "407": "Naša kapusta raste v sadě.",
  "408": "Rěpa jest sladka i červena.",
  "409": "Mrkva jest oranževa i zdrava.",
  "410": "Pripravi supu iz mrkvy.",
  "411": "Ta podlivka jest velje ostra.",
  "412": "Pripravi salatu s oljejom.",
  "413": "Na deser budem jesti kolač.",
  "414": "Pijem čaj s mleком.",
  "415": "Kava jest goryča.",
  "416": "On pije pivo s prijateli.",
  "417": "Červeno vino jest dobro s syrom.",
  "418": "Kupil jesm svěžu bulku.",
  "419": "Hlěb jest na stoli.",
  "420": "Mama spekla kolač za jutro.",
  "421": "On ne jede glutena.",
  "422": "Svinina jest na trelice.",
  "423": "Govedina jest v supi.",
  "424": "Jajca sut na talirki.",
  "425": "Děti ljubet sladkosti.",
  "426": "Fasolja jest v supi.",
  "427": "Grah jest zeleny i sladky.",
  "428": "Paprika jest oranževa i krasna.",
  "429": "Cibulja jest ostra.",
  "430": "Česnok ima silny vonj.",
  "431": "Orěh jest tvrd.",
  "432": "Jabloky rastu na drevě.",
  "433": "Gruša jest sladka i myagka.",
  "434": "Jagody sut červeny i vkusny.",
  "435": "Sliva jest modra i sladka.",
  "436": "Banan jest žolty i sladky.",
  "437": "Ananas raste v toplom kraju.",
  "438": "Grozdje jest sladko.",
  "439": "Pomaranča jest oranževa.",
  "440": "Limon jest kisely.",
  "441": "Drži ruky v kěšenjah i svistaje. -- Titus, Romek i A'tomek",
  "442": "On podal mi dlanj na pozdravljenje.",
  "443": "Ona lomila nogu zprěd treh lět.",
  "444": "Glava me boli.",
  "445": "Ona ima krasno lice.",
  "446": "Vse v rukah člověka i vse to on mimo nosa propušča. -- Prěstupanje i ukaranje",
  "447": "Ona ne slyšit dobro levym uhom.",
  "448": "Jej oko jest sinje.",
  "449": "Zrěnje mu jest slabo.",
  "450": "Zub mě boli, treba idti k lěkaru.",
  "451": "Boli mě brjuho posle jediva.",
  "452": "Boli mě hrebet posle dolgoj raboty.",
  "453": "Ona ima dluge vlasy.",
  "454": "Moj jezyk ne može togo rěkti.",
  "455": "Boli mě prst.",
  "456": "Ona maljuje svoji nогty.",
  "457": "Pasti na zadnicu jest smješno.",
  "458": "Koleno boli posle boga.",
  "459": "Stopa boli od dolgoj hody.",
  "460": "Lěkar kazal, čto kost jest pereломena.",
  "461": "Krov jest vidna na rani.",
  "462": "Vena jest viditna na ruci.",
  "463": "S zamirajučim srdcem i nervoznym drženjem podšel on k ogromnomu domu. -- Prěstupanje i ukaranje",
  "464": "Moj želudok boli.",
  "465": "Jetra jest važny organ.",
  "466": "Pljuča potrěbujut čist vozduh.",
  "467": "Črěvo boli po jedivě.",
  "468": "Ta věč jest moja.",
  "469": "Ona kupila novo oblěčenje.",
  "470": "Moji obuvky sut mokry.",
  "471": "Šapka ta byla vysoka, krugla, zimmermanovska... -- Prěstupanje i ukaranje",
  "472": "On oblěkl plašč i išel von.",
  "473": "Ta košulja jest sinja.",
  "474": "Moje nogavice sut mokre.",
  "475": "On nosi sako na rabotu.",
  "476": "Žilet jest pod sakom.",
  "477": "Ona ima krasnu suknju.",
  "478": "Na svadbu on nosil klasičny kostjum.",
  "479": "On nosi naočila dlja čitanja.",
  "480": "Vzemi doždnik, bude dožd.",
  "481": "Tvoje rukavice sut pod stolom.",
  "482": "Škarpetki sut v kufri.",
  "483": "Gače sut v pranje.",
  "484": "Ona kupila nove stringi.",
  "485": "On spavaje v pižami.",
  "486": "Jeduči na velоsipedu, nosim šlěm.",
  "487": "Kosmetika jest v małoj torbi.",
  "488": "Ten krem jest dobry za ruce.",
  "489": "Dezodorant jest v kupaljnji.",
  "490": "On vzal zapalničku i razžeg svěčku.",
  "491": "Vsegda beri prezervativ.",
  "492": "Lěkar vzal špric.",
  "493": "Vzemi nožice i ostriži.",
  "494": "Ona nosi lyže v gorach.",
  "495": "Děti jezdet na slizajkah po ledu.",
  "496": "On krade na roljkah v parku.",
  "497": "Daj mi kruglu!",
  "498": "Vitez nosi mečy.",
  "499": "Vojak drži ščit.",
  "500": "Oružje jest opasno.",
  "501": "On daroval jej krasny prstenj.",
  "502": "Ona nosi zlaty nagrdelnik.",
  "503": "Moj dar tebě jest ta kniga.",
  "504": "Pijte mnogo vody každy denj.",
  "505": "Morje jest sinje i temno.",
  "506": "Okean jest prěveliky.",
  "507": "Jezero jest blizko gory.",
  "508": "Rěka teče prěz lěs.",
  "509": "My idemo na plaž jutro.",
  "510": "Děti igrajut na pěsku.",
  "511": "Na tom ostrovu žive malo ludej.",
  "512": "Korab jest v zatoki.",
  "513": "Kanal prěz to město jest stary.",
  "514": "V pustynji jest velě žarko.",
  "515": "Spali jesmo pod golym nebom.",
  "516": "Noču vidno mnogo zvězd.",
  "517": "Idemo v gory na vikend.",
  "518": "Ta skala jest visoka i opasna.",
  "519": "V lěsě jest tiho i mirnо.",
  "520": "Drěvo raste prěd našim domom.",
  "521": "Oves raste v sadě.",
  "522": "Zeleny list padl na zemju.",
  "523": "Korenj togo drěva jest veliky.",
  "524": "Větka s cvěty jest krasna.",
  "525": "Trava jest zelena i myagka.",
  "526": "Krava pase se na poljaně.",
  "527": "Cvět raste v sadě.",
  "528": "V lěsě nahodiš mnogo gribov.",
  "529": "Na polju rastut žita.",
  "530": "Bagno jest opasno za hodžu.",
  "531": "Zima hladno, oblecy se teplo.",
  "532": "Jutro jest teplo i solnečno.",
  "533": "Mraz ščipje lice.",
  "534": "V avguste byva velika gorečnja.",
  "535": "Solnce sijaje každy denj v lětě.",
  "536": "Dožd padaje iz oblakov.",
  "537": "Děti ljubet igrati v sněgu.",
  "538": "Led na rěci jest tонky.",
  "539": "Burja razrušila nješkoliko domov.",
  "540": "Oblak zakryl solnce.",
  "541": "Děti bavet se na svěžem vozduhu.",
  "542": "Větr otvoril okno.",
  "543": "Naš grad jest veliky i krasny.",
  "544": "To jest krasno město na gori.",
  "545": "Kupil jesm hlěb v magazinĕ.",
  "546": "Provodi mladca črěz ulicu. -- Titus, Romek i A'tomek",
  "547": "Děti idut do školy každy denj.",
  "548": "Crkva jest stara i krasna.",
  "549": "Parkovišče jest za budynkom.",
  "550": "Restoran na uglě je dobry.",
  "551": "On byl prevežen do boljnice.",
  "552": "Vlak odhodit se od stancije.",
  "553": "Naša platforma jest devjata.",
  "554": "Most prěz rěku jest visok.",
  "555": "Ogonj v lěsě jest opasny.",
  "556": "Ne imal jesm dost grošej.",
  "557": "Cěna togo avta jest visoka.",
  "558": "Prinesete mi rahunok, prosim.",
  "559": "Ostavi napojnicu kellnerovi.",
  "560": "Plačo kartoju, ne gotovinom.",
  "561": "Hotěl byh kupiti novu knigu.",
  "562": "On prodal svoj avto.",
  "563": "Izgleda, že jedino ja budem platiti vnosy. -- Titus, Romek i A'tomek",
  "564": "Zaplatil jesm za oběd.",
  "565": "Koliko koštuje ta suknja?",
  "566": "Zloděj ukral moj telefon.",
  "567": "V tom magazinĕ vsě prodajut deševo.",
  "568": "To avto jest prědrago dlja mene.",
  "569": "Platio jesm gotovinom.",
  "570": "Plati pri kasě.",
  "571": "V pjatok jest razprodaž v magazini.",
  "572": "Na etom sajtě byva obniženje cěn.",
  "573": "On dal nam veliky rabat.",
  "574": "Kava s soboju, prosim.",
  "575": "Rěci mi pravdu.",
  "576": "Ne govori ložy.",
  "577": "Imam jedno pytanje k tebě.",
  "578": "Ona ne dala mi odpověd.",
  "579": "Imamo veliky problem s projektom.",
  "580": "Nahodimo rěšenje zajedno.",
  "581": "To byja moja pogrěška.",
  "582": "Ona sdělalja grěšku.",
  "583": "V etom programu jest hyba.",
  "584": "Avto ima defekt.",
  "585": "Oprava steny budet stojati drago.",
  "586": "Imali jsme dolgy razgovor.",
  "587": "Vsi idut na zabavu.",
  "588": "Imali jsme razprju o toj temě.",
  "589": "Sustrěča jest v srědu.",
  "590": "To byjo važno sobytje.",
  "591": "Toj slučaj jest poučny.",
  "592": "Neščestny slučaj na dragi byl rano jutro.",
  "593": "Vojna jest strašna věč.",
  "594": "Vsegda hočem žiti v pokoji.",
  "595": "On ljubi svoju rabotu.",
  "596": "Učenje językov jest zabavno.",
  "597": "Ona ima znanje medžuslovjanskogo.",
  "598": "Nu, zatom načinamo praktikovanja. -- Titus, Romek i A'tomek",
  "599": "Moje mněnje jest razno.",
  "600": "On sděla dobro vraženje na nas.",
  "601": "Na vakacije idemo k morju.",
  "602": "Toj zakon naredžaje platiti.",
  "603": "Imam dobru ideju!",
  "604": "Kako to je dobry sposob?",
  "605": "Jej naměr byl pomoči nam.",
  "606": "On ima ostry razum.",
  "607": "Buduči astronavt musi zadržati trězvost uma v každoj situaciji. -- Titus, Romek i A'tomek",
  "608": "Kakoě jest značenje togo slova?",
  "609": "Svoboda jest dragocěna.",
  "610": "Jest možnost pomogti?",
  "611": "Ih svezok jest silny.",
  "612": "Uslovje jest prosto.",
  "613": "Koliko čislo sut tu?",
  "614": "Kakoj jest kolikost?",
  "615": "Kakost togo produkta jest visoka.",
  "616": "Točnost jest važna v toj rabotě.",
  "617": "Osnova projekta jest dobra.",
  "618": "Na početku bylo težko.",
  "619": "My jesmo na koncu toj dragi.",
  "620": "Nedostatok vody jest problem.",
  "621": "Ona ima alergiju na pticu.",
  "622": "Zdravje jest najvažněja věč.",
  "623": "Hvоroba prišla naglo.",
  "624": "Kakova jest srědina?",
  "625": "Budem gledati z obih stran.",
  "626": "To jest mala čest našego plana.",
  "627": "Vzeli jsme cělost etogo problemu.",
  "628": "Dviženje togo avta bystro.",
  "629": "Jej glas jest mягky i krasny.",
  "630": "Zvuk muzyky jest glasny.",
  "631": "Muzika nas veseli.",
  "632": "Jego izgled jest krasny.",
  "633": "Vonj květov jest krasny.",
  "634": "Pogled na morje jest prěkrasny.",
  "635": "Njegova ljubov k njej jest silna.",
  "636": "Radost děcej razveselit vsih.",
  "637": "Ščestje jest v malyh věčah.",
  "638": "Smutok prišel posle poměšelja.",
  "639": "Słyšim plač děceta.",
  "640": "Strah ne pomaže, treba dějati.",
  "641": "Bezpokojstvo jest lišno.",
  "642": "Bolj v ruci jest silna.",
  "643": "Jej nastroj se izměnil naglo.",
  "644": "Muzika mi daje prijemnost.",
  "645": "Bezpečnost děcej jest važna.",
  "646": "Dověrje gradi silne svezki.",
  "647": "Naš dobry sused vsegda pomage.",
  "648": "Ta lěpša metoda pomage.",
  "649": "To jest najlěpša kniga co čital jesm.",
  "650": "Zły čas prošel, vsě budet dobro.",
  "651": "Situacija byja gorša nego myslil jesm.",
  "652": "To byl najgroši denj mojego žitja.",
  "653": "Oni živut v velikom domu.",
  "654": "To děte jest malo i krasno.",
  "655": "Srědnja cěna jest dobra.",
  "656": "Ta gora jest vysoka.",
  "657": "On govori tiho i nizko.",
  "658": "Ta draga jest dolga.",
  "659": "Věr jest kratky.",
  "660": "Ona ima krasno lice.",
  "661": "Ten muž jest bridky i nekrasny.",
  "662": "Bystry avto pojehал prěz most.",
  "663": "Medla čerpaha hodi po poljaně.",
  "664": "Ta matematika jest trudna dlja mene.",
  "665": "Toj kamjon jest velje težky.",
  "666": "Ta zadača jest legka.",
  "667": "Legky rjukzak je lěpši dlja putovanja.",
  "668": "Naša kuhnja jest vsegda čista.",
  "669": "Nečisty stol treba umyti.",
  "670": "Ta draga jest nebezpečna noću.",
  "671": "To jest važna věč, ne zapominajte.",
  "672": "Medžuslovjansky jest zajmlivy język.",
  "673": "Ta kniga jest nudna.",
  "674": "- pomyslil on so strannym usměhom. -- Prěstupanje i ukaranje",
  "675": "Ta situacija jest směšna.",
  "676": "Ona kupila novy kompjuter.",
  "677": "To jest moja prva rabota.",
  "678": "Ona jest drugy raz zamužem.",
  "679": "To jest moja poslědnja šansa.",
  "680": "V poprědnjem godě vsě bylo ino.",
  "681": "Nastupny vlak bude za hodinu.",
  "682": "Iny sposob jest lěpši.",
  "683": "To jest različny produkt.",
  "684": "V tom magazini sut različne veci.",
  "685": "Imamo raznorodne ideje.",
  "686": "Toj dom jest podobny k našemu.",
  "687": "My živemo v jednakom domu.",
  "688": "On myslije inako nego ja.",
  "689": "Avto jest poškodženo.",
  "690": "Moja torba jest polna.",
  "691": "Stakan jest pusty.",
  "692": "On jest zajety vsе vrěme.",
  "693": "Vaš soběd jest potrěbny.",
  "694": "To jest nužno dlja tvoje zdravja.",
  "695": "Voda jest neobhodima dlja žitja.",
  "696": "Pasport jest obvezny dlja putovanja.",
  "697": "On byl dolžny vokrug gospodynji i bojal se s njeju strěsti. -- Prěstupanje i ukaranje",
  "698": "Ten soběd jest koristny.",
  "699": "Ta stolka jest vygodna.",
  "700": "To jest prigodna opcija.",
  "701": "To je uměstny otgovor.",
  "702": "Něčto se stalo. Pogledatelj ne odgovorja. -- Titus, Romek i A'tomek",
  "703": "To jest umětny material.",
  "704": "Etaj park jest obča věč.",
  "705": "On govori čudžim językom.",
  "706": "Ona jest ščestliva s novoju rabotoju.",
  "707": "On jest rad s rěšenjm.",
  "708": "Ona jest smutna posle rozluki.",
  "709": "On byj udivjeny kadarom.",
  "710": "Vsе byhu udivjeny toj věstju.",
  "711": "On byl prěstrašeny glasnym zvonom.",
  "712": "On jest srdity na nas.",
  "713": "Ona jest smučena situacijom.",
  "714": "Děte jest bezpokojno nochu.",
  "715": "On jest razdraženy moim pytanjam.",
  "716": "Ona jest gorda na svojogo syna.",
  "717": "On jest nesmělivy na novom místě.",
  "718": "Dodava sobě hrabrosti. -- Titus, Romek i A'tomek",
  "719": "Bědna rodina potrěbuje pomoč.",
  "720": "Bogaty muž žive v velikom domu.",
  "721": "On jest nepodatlivy i ne slušaje.",
  "722": "Posle dolgoj dragi ja jest utomljeny.",
  "723": "Ta rabota jest umarjajuča.",
  "724": "Posle maratona on byj umorjeny.",
  "725": "Ona jest mila i pomaga vsim.",
  "726": "On jest čestny muž.",
  "727": "On jest zdravy i silny.",
  "728": "Boljny muž leži v posteli.",
  "729": "Stary dom treba renovirati.",
  "730": "Mlady muž teče bystro.",
  "731": "Silny muž nosi těžky kamen.",
  "732": "Slaby zvuk z daleka.",
  "733": "Ja imam malu sestru.",
  "734": "Ta firma uže ne istnovajet.",
  "735": "Ona umějet govoriti pятy językov.",
  "736": "Može li on priti zautra?",
  "737": "On smogel dokončiti rabotu v čas.",
  "738": "Projekt nam udal se.",
  "739": "Ona uspěla v novoj firmě.",
  "740": "My uspěli priti v čas.",
  "741": "Musěti zaplатiti za vsě.",
  "742": "Ty povinen pomoči im.",
  "743": "Potrěbojeme novogo računara.",
  "744": "Ona ljubit čitati knigy.",
  "745": "On ljubit svoju ženu i děti.",
  "746": "Imaju naděju vidětī tebe skoro.",
  "747": "On žije v Prazi uže pjet lět.",
  "748": "Ona žije i ljubit každy denj.",
  "749": "Čto značit to slovo?",
  "750": "Ta kniga prinaleži knjižnici.",
  "751": "To tyče se tebe i mene.",
  "752": "Čto ty dělaješ tutčas?",
  "753": "Ona sdělala dobro delo.",
  "754": "Avto dviže se bystr.",
  "755": "Drži knigu v obih rukah.",
  "756": "Zadržite avtо!",
  "757": "On shvatil loptu.",
  "758": "Kamo ty ideš?",
  "759": "Ona prišla domov pozdno.",
  "760": "Ona prihodit každy denj v šest.",
  "761": "On běži bystro prěz park.",
  "762": "Ona běgaje každo jutro v parku.",
  "763": "Jehali jsme do mora s rodinoju.",
  "764": "Vlak prijede v tri.",
  "765": "Ptice letut na jug na zimu.",
  "766": "Naš let priletěl v čas.",
  "767": "Ona plyve v jezeru.",
  "768": "Korab plove po morju.",
  "769": "On plavaje každo jutro.",
  "770": "Prinositi kavu každo jutro.",
  "771": "Ona prinesla nam hlěb.",
  "772": "Prenesti knigy do inoj komnaty.",
  "773": "On vozdvignul těžky kamen.",
  "774": "Kydnut loptų visoko.",
  "775": "Ona stoji prěd školojom.",
  "776": "Vstani rano i pripravi se.",
  "777": "...lěpje proslizgnuti se kako-nebud i izběgnuti, da by nikto ne viděl. -- Prěstupanje i ukaranje",
  "778": "Tegnuti za konec vrvi.",
  "779": "Ona skočila prěko potoka.",
  "780": "Oni tancujet na věčerě.",
  "781": "On pěvaje krasno.",
  "782": "Děti igrajut v sadu.",
  "783": "Naša komanda izigрала!",
  "784": "On proigral v šahah.",
  "785": "Obježdžali jsme staro město.",
  "786": "Čekajte mene, skoro pridu.",
  "787": "On govori medžuslovjansky dobro.",
  "788": "Skaži mi pravdu.",
  "789": "On kazal vsim tihо stati.",
  "790": "Pytala jsem lěkara o lěčenju.",
  "791": "Zapytala jsem o daragě.",
  "792": "On pomagaje nam vsegda.",
  "793": "Ona pomogla mi s zadanjom.",
  "794": "On izbavil děte od opasnosti.",
  "795": "On pozvaljaje nam priti.",
  "796": "Šef pozvolil nam oditi raněje.",
  "797": "Strěteli jsme se v parku.",
  "798": "On žartovaje vsegda.",
  "799": "Ona zvonit mi každy denj.",
  "800": "Pozvonił jesm prijatelju.",
  "801": "Šef pobudžajet rabotnikov.",
  "802": "Ne moge ubědžati go.",
  "803": "Ona hvali rabotu svogo syna.",
  "804": "Kritikovati bez razuma jest liho.",
  "805": "Ona nagradžala dobreho rabotnika.",
  "806": "On byl pokarany za ту grěšku.",
  "807": "Firma dala rabotu sto novym ludjem.",
  "808": "On byl izvoljněn posle rok.",
  "809": "Ona daваje mi knigy každy měsec.",
  "810": "Daj mi to, prosim.",
  "811": "On bere knigu z stola.",
  "812": "Vzmi knigu i čitaj.",
  "813": "On dostaaje poslanija každy denj.",
  "814": "Pozajel jesm knigu od prijatelja.",
  "815": "Dati zajem dengy prijatelju.",
  "816": "Vojaci bojevahu za svobodu.",
  "817": "Ja věrju tebě.",
  "818": "Čuju tvoj glas.",
  "819": "Ne dotykaj se togo!",
  "820": "Viděl jesm tebe včera.",
  "821": "Uvidal jesm krasny cvět.",
  "822": "Gledaj na nebo.",
  "823": "Pozri na totu knigu.",
  "824": "Obdivjaju krasotu toj gory.",
  "825": "Slyšu muziku iz ulice.",
  "826": "Slušajte učitelja.",
  "827": "Uslyšal jesm glas iz daleka.",
  "828": "Pas njuhaje vsje.",
  "829": "Oni jedut za stolom.",
  "830": "Sjela jsem vsě pirogy.",
  "831": "Pijem vodu každy denj.",
  "832": "Napil jesm se mlěka.",
  "833": "Izpi tu kavu.",
  "834": "Ona spi do devjet časin.",
  "835": "Zasnu bystrо posle trudnogo dnja.",
  "836": "On ubil zmiju v sadě.",
  "837": "Stary pes umrl minule lěto.",
  "838": "Lěkar lěčit bolnogo.",
  "839": "Odpočivati posle raboty jest važno.",
  "840": "Ona cělovaje děte na dobru noč.",
  "841": "On rabotaje v toj firmi deset lět.",
  "842": "Ona zarabotyvajet dobry khlěb.",
  "843": "On myslije o novom proekte.",
  "844": "Ona izmyslila novy sposob.",
  "845": "Razuměju te dobro.",
  "846": "On srazuměl situaciju.",
  "847": "Poznala jsem novu kolegicu.",
  "848": "Učim se medžuslovjansky každy denj.",
  "849": "Naučil jesm se novo slovo.",
  "850": "Ona studiujet medicinu v universitětě.",
  "851": "Iz togo izveli smo zaključok.",
  "852": "Izobrazite si lěpšu žizn.",
  "853": "On izměnil mněnje posle razgovora.",
  "854": "Ona pametaje vsě děni.",
  "855": "Ne zabyti knigu doma.",
  "856": "Pripoměni mi o tom.",
  "857": "Pomylil jesm se v tom voprosi.",
  "858": "On naměruje otiti jutro.",
  "859": "Izdava se, čto ona ne jest doma.",
  "869": "Prověri, či prišel poslanij.",
  "870": "Treba prěgleděti vsě dokumenty.",
  "871": "Lěkar raziskal pacienta.",
  "872": "Ocěni situaciju prěd dějanjem.",
  "873": "Izbirajem meju dvěma opcijama.",
  "874": "Ona izbrala novu rabotu.",
  "875": "On čitaje knigu každu večerju.",
  "876": "Pročitala jesm vsю tu knigu.",
  "877": "Ona piše pismo prijatelju.",
  "878": "Napiši mi svoj adres.",
  "879": "Izgubil jesm svoj pasport.",
  "880": "On išče svoje knigy.",
  "881": "Najde knigu na stolu.",
  "882": "Myjem ruce prěd jedivom.",
  "883": "Umyi lice prěd odhodom.",
  "884": "Otvarjati okno rědin.",
  "885": "Otvori dveri, prosim.",
  "886": "Zatvarjati okna noču.",
  "887": "Zatvorila jsem vrata na ključ.",
  "888": "Pokaži mi daragу na karti.",
  "889": "Ukryi knigu pod stolom.",
  "890": "Shovaj moj dar do jego príhoda.",
  "891": "Odstrani vsje stare dokumenty.",
  "892": "Podkjuči kompjuter k sěti.",
  "893": "Pridaj solje v supu.",
  "894": "On popravil avto.",
  "895": "Izniščiti stary mebel.",
  "896": "Izměni bateriju v časovniku.",
  "897": "Izpolni formuljar svojimy danymi.",
  "898": "On začinajet novy projekt jutro.",
  "899": "Začeti govoriti o problemu.",
  "900": "Ona končajet rabotu v šest.",
  "901": "On skončil pismo.",
  "902": "Poezdka trvajet tri časiny.",
  "903": "Probuj opět!",
  "904": "Povtarjajte slova každy denj.",
  "905": "Povtori odgovor gromko.",
  "906": "On ostaje doma tutčas.",
  "907": "Ona stala lěkarom.",
  "908": "Prihodit s mnojom.",
  "909": "On prišel bez torby.",
  "910": "Vsí prihodet kromě Marka.",
  "911": "Pomimo dožda, idemo von.",
  "912": "Vzemi moju knigu vměsto tvoje.",
  "913": "Pod stolom leži pas.",
  "914": "Ptica leti nad domom.",
  "915": "Avto stoji pred vhodom.",
  "916": "Ona sedi za domom.",
  "917": "Škola jest medžu parkom i rěkojom.",
  "918": "On stoji pri okni.",
  "919": "Apteka jest podle naše školy.",
  "920": "Kniga leži na stolu.",
  "921": "Živi v malem domu v lěsě.",
  "922": "Voda tečet iz rěky.",
  "923": "Pismo od mamy prišlo.",
  "924": "Čekamo do tri časiny.",
  "925": "Idemo k prijatelju.",
  "926": "Lěpi vodu v čašku.",
  "927": "Ten dar jest dlja tebe.",
  "928": "Ta suknja jest za večerju.",
  "929": "Za tri dny vrnemo se.",
  "930": "Vsě sut protiv togo plana.",
  "931": "Čto jest vnutri tej torby?",
  "932": "Vně jest hladno.",
  "933": "Idemo črěz park.",
  "934": "Vsečto jest gotovo.",
  "935": "Vsi prihodet na večerju.",
  "936": "Někto klуčajet na dveri.",
  "937": "Hočeš něčto rěkti?",
  "938": "Čtokoli rěkneš, ja slušaju.",
  "939": "Čto-nebud kupie nam.",
  "940": "Někaky muž pytajet te.",
  "941": "Kniga jest někde v toj komnate.",
  "942": "To jest něčij telefon.",
  "943": "On odhodi někamo každy večer.",
  "944": "Budem někako rěšiti ten problem.",
  "945": "Idemo někudy prěz lěs.",
  "946": "Něčemu on ne prišel.",
  "947": "Kojkoli den jest dobry dlja raboty.",
  "948": "Vse ravno, gde jemo.",
  "949": "Na priměr, možeš rěkti 'dobry denj'.",
  "950": "On govorit dobro, čto vyše, on piše krasno.",
  "951": "Imenno to imaju v mysli.",
  "952": "Každy muž ima svoju doragu.",
  "953": "Žaden iz ih ne priide.",
  "954": "Oba brata priidu jutro.",
  "955": "Idemo zajedno v park.",
  "956": "Oni živut oddělno.",
  "957": "Točno to imaju v mysli.",
  "958": "On ne rěkе ničto.",
  "959": "Nikto ne znaet toj tajny.",
  "960": "Ona nikogda ne late.",
  "961": "Nikde ne nahodiml toj knigy.",
  "962": "On zna vsede vsih.",
  "963": "Črvena roža jest moja ljubima.",
  "964": "Trava jest zelena v lětě.",
  "965": "Nebo jest modro.",
  "966": "Moj avto jest črny.",
  "967": "Ona nosi bělу suknju.",
  "968": "Solnce jest žolte.",
  "969": "On kupi oranževo jabоlko.",
  "970": "Ona ima rozovu košulju.",
  "971": "Fioletovy cvět jest krasny.",
  "972": "Medvěd jest koričnevy.",
  "973": "Nebe jest sěro i oblačno.",
  "974": "On ima zlate vlasy.",
  "975": "Ona nosi srěbrny prstenj.",
  "976": "V ponedělok imam važnu sustrěču.",
  "977": "Vtorok jest trudny denj.",
  "978": "V srědu imamo sustrěču.",
  "979": "V četvrtok prihodit naš klient.",
  "980": "V petok vsě radujut se.",
  "981": "V subotu idemo v gory.",
  "982": "Nedělja jest denj odpočinoka.",
  "983": "Januar jest najhladněji měsec goda.",
  "984": "Fevruar je kratky měsec.",
  "985": "V mareci sněg taje.",
  "986": "V aprilu cvěte sad.",
  "987": "V maju vsje zeleno.",
  "988": "Junij jest teplo a solnečno.",
  "989": "V juliju idemo na plaž.",
  "990": "Avgust jest naj gorěči měsec.",
  "991": "V septembri děti idut v školu.",
  "992": "V oktobrě listi padajut.",
  "993": "V novembri jest hladno i sěro.",
  "994": "Dekembr jest měsec darkov.",
  "995": "Vesna jest moje ljubimo vrěme goda.",
  "996": "V lětě idemo k morju.",
  "997": "Jesenj jest krasna s červenymi listami.",
  "998": "V zimu pada sněg.",
  "999": "Město jest na sěverě zemje.",
  "1000": "Naš grad jest na jugu.",
  "1001": "Solnce vshodi na vozhodi.",
  "1002": "Větr prišel z zapada.",
  "1003": "Možno jest da prideš jutro?",
  "1004": "To jest nemožno.",
  "1005": "Malo pravdopodobno jest, čto on prideт.",
  "1006": "Može, ona prideт po obědi.",
  "1007": "Věrojetno on zabyl.",
  "1008": "Pravdopodobno ona jest doma.",
  "1009": "Uvěrjeno prideт jutro.",
  "1010": "Isto, ona znajet otgovor.",
  "1011": "Nesumněno, to jest pravda.",
  "1012": "Izdava se, že on ne razuměet.",
  "1013": "On i ja idemo zajedno.",
  "1014": "Kava ili čaj?",
  "1015": "Ja rabotaju, a ona učit se.",
  "1016": "On govorit a takože piše dobro.",
  "1017": "Ili ty ideš, ili ja.",
  "1018": "Ni on ni ona ne pridet.",
  "1019": "On hotěl priti, ale byl boljny.",
  "1020": "Ona jest starěja než ja.",
  "1021": "Myslim, že on prideт.",
  "1022": "On byl boljny, tako ne prišel.",
  "1023": "Govori glasno, tako že vsě slysят.",
  "1024": "On byl slaby, zatom ne prišel.",
  "1025": "Prišla aby pomogti.",
  "1026": "Prosim da by on prišel.",
  "1027": "Hot on byh boljny, pришel.",
  "1028": "Ne prišel, tomu že był boljny.",
  "1029": "Ne prišel, ibo byh boljny.",
  "1030": "Ne prišel po pričině bolezny.",
  "1031": "Vslěd neplaxenija, ugovor byl rasторгnut.",
  "1032": "Hvala tебe, smogła pomoči.",
  "1033": "Tomu on prišel sam.",
  "1034": "Radi zdravja treba spati dobro.",
  "1035": "Radi firmy, on rabotajet dvadset četyre hodin.",
  "1036": "Soglasno pravilam, vsě treba platiti.",
  "1037": "Podolg novosti, on uže jest doma.",
  "1038": "Ako prideš, javijte se.",
  "1039": "Ne pridu, ako ne pozvoniš.",
  "1040": "Ne znam, či on prideт.",
  "1041": "On hotěl priti, jednako ne mog.",
  "1042": "Daže děti razumejut to.",
  "1043": "Bylo tak těžko, až plakala.",
  "1044": "Jedino ty možeš pomoči mi.",
  "1045": "Govorit kako by on byh boljny.",
  "1046": "On takože govorit po-russky.",
  "1047": "V parku byho mnogo ludej.",
  "1048": "Kupili smo mnogo jediva.",
  "1049": "Bylo bardzo mnogo dožda.",
  "1050": "Nemnogo knig ostalo.",
  "1051": "Imam několiko pytanj.",
  "1052": "Malo mlěka jest v skljanki.",
  "1053": "Bylo velmi malo vrěmeny.",
  "1054": "Ona jest velmi mila.",
  "1055": "Hoću vyše kаvy.",
  "1056": "To jest najvyše čto možemo dati.",
  "1057": "Ten gory jest vyše nego toj.",
  "1058": "On čita vse bolje.",
  "1059": "Daj mi veče soli.",
  "1060": "Imam menje vrěmeny.",
  "1061": "Prišlo menje ludej nego čekali jsme.",
  "1062": "Najmenje što možeš sdělatи.",
  "1063": "On žive niže v dolině.",
  "1064": "Větr dul silno.",
  "1065": "On biji avto močno.",
  "1066": "Svěča gorěła slabo.",
  "1067": "Daj mi trohu soli.",
  "1068": "Ne piją prěmnogo alkohola.",
  "1069": "On bliz zabyл.",
  "1070": "Byl jednoraz v Parizi.",
  "1071": "Posetil jesm Pragu dvukratno.",
  "1072": "On jedva priidu v čas.",
  "1073": "Zadanje jest dost prosто.",
  "1074": "Sovšem ne razuměm.",
  "1075": "On vzal pol kolača.",
  "1076": "On sjel cěly kolač.",
  "1077": "Na žalost, on ne prišel.",
  "1078": "To napravdu jest divno.",
  "1079": "Vsе jest v poredku.",
  "1080": "Jedno uslovje jest nužno.",
  "1081": "Dodaj cukr v čaj.",
  "1082": "Moji roditelji živut v malom selu.",
  "1083": "Byha smo na ekskursiji v Pragi.",
  "1084": "On žive v malom selu.",
  "1085": "Věd ty znaješ odgovor!",
  "1086": "Ten soběd mi prigodil se.",
  "1087": "Ne nepokoji se, vsё budet dobro.",
  "1088": "Ne bezpokoj mene!",
  "1089": "Prišla mi vědomost od prijatelja.",
  "1090": "Najvažny punkt jest treti.",
  "1091": "V tom domu jest mnogo prostora.",
  "1092": "On boji se temoty.",
  "1093": "Pomsta jest sladka, ale opasna."
};
