const EXAMPLES = {
  "1": "Da, ja razuměm tebe.",
  "2": "Ne, to ne jest moja torba.",
  "3": "Čije sut one? Ne znaju. Ničije. -- Maly Princ",
  "4": "Ja ne razuměju čto ty govoriš… -- Maly Princ",
  "5": "Očevidno, postaraju se, že by moje portrety byli koliko možno věrne. -- Maly Princ",
  "6": "Ahoj, kako jesi?",
  "7": "Čao, vidimo se zautra!",
  "8": "Dobro jutro! Spala jesi dobro?",
  "9": "Dobry denj! Vhodite, prosim.",
  "10": "«Dobry večer», rěkla zmija. -- Maly Princ",
  "11": "My izhodimo. Do viděnja!",
  "12": "Ja mušu uže idti. Vidimo se!",
  "13": "Dobra noč, spi dobro.",
  "14": "Kako jesi, prijatelju?",
  "15": "Prijatny denj vam želam!",
  "16": "Dekujem — vzajemno!",
  "17": "Dekujem za pomoč.",
  "18": "Nema za čto, to jest moja dolžnost.",
  "19": "Prosim, daj mi vodu.",
  "20": "Prosim, vot tvoja karta.",
  "21": "Izvinite, kde jest toalet?",
  "22": "Žal mi je, ale nič lěpše ne iměli jesmo pod rukom. -- Titus, Romek i A'tomek",
  "23": "Dobrogo apetita, jedite!",
  "24": "Dostala je prěkrasno ime od svojego otca. -- Nehaj nas nesut...",
  "25": "Moje prězime jest Novak.",
  "26": "Nazyvam se Marek.",
  "27": "Ja jesm iz krilanskogo roda. -- Nehaj nas nesut...",
  "28": "Ale začto hočeš, že by tvoje ovce jedali male baobaby? -- Maly Princ",
  "29": "Ja htěl byh uviděti zapad solnca... -- Maly Princ",
  "30": "Želam ti mnogo ščestja.",
  "31": "Možemo govoriti na medžuslovjanskom.",
  "32": "Možem li vzeti tutu knigu?",
  "33": "Musim uže idti k domu.",
  "34": "Ostražno! Avto jede bystro.",
  "35": "Pomoči! Ja ne uměm plavati!",
  "52": "To jest najumnějši člověk na tutoj planetě. -- Maly Princ",
  "53": "Tamtoj muž jest naš učitelj.",
  "54": "Ne! Tuta jest uže mnogo boljna. Izdělaj mi drugu. -- Maly Princ",
  "55": "Tamta kniga jest stara.",
  "56": "Tuto jest kopija ovoj rysovanky. -- Maly Princ",
  "57": "Tamto děte plače.",
  "58": "Ne jest potrěbno, že byh žil tu. -- Maly Princ",
  "59": "Moj brat žije tam, za gorami.",
  
  "60": "Kto jest toj muž?",
  "61": "Čto ty dělaš?",
  "62": "Kogo ty vidžiš tam?",
  "65": "O kom on govori?",
  "66": "S kym ty idžeš na večerju?",
  "67": "Čija jest ta kniga?",
  "68": "Kde jest najblizša apteka?",
  "69": "Kogda ty prijdeš v dom?",
  "70": "Kak ty se čuješ?",
  "71": "Začto ty plačeš?",
  "72": "Začto ty to kupil?",
  "73": "Koliko to koštuje?",
  "74": "Ktory avtobus ide do centra?",
  "75": "Ktora kniga jest najlěpša?",
  "76": "Težko jest nadti dobru njanju dlja děteta… Ale ješče težje jest nadti dobro děte. -- Andrzej Mleczko" 
  "77": "Odkud ty jesi prijehal?",
  "78": "Dokud ty ideš?",
  "79": "Kudy musimo jehati že by ne platiti za avtostradu?",
  "80": "Odkogda ty učiš se medžuslovjansky?",
  "81": "Dokolě budete čekati?",
  
  "82": "Naše avto jest staro ale dobro.",
  "83": "Avtobus jede k stanciji.",
  "84": "Vlak bude prijehati v šestoj časině.",
  "85": "Samolet leti vysoko.",
  "86": "On jezdi na velosipedu vsakodenno.",
  "87": "Děti vozet se na samoběžkě po parku.",
  "88": "Veliky korab plove po morju.",
  "89": "Větrilo na lodi jest bělo.",
  "90": "Veliky kamion blokuje dragu.",
  "91": "Vhod jest tam, za uglom.",
  "92": "Izhod iz budynka jest vsegda otvorjeny.",
  "93": "Vjezd v grad jest zamknuty.",
  "94": "Izjezd iz avtostrady jest blizko.",
  "95": "Ta draga vede k morju.",
  "96": "Na avtostradu možeš jehati bystro.",
  "97": "Na tom viraže budi ostražny.",
  "98": "Na tom križišču treba stati.",
  "99": "Idi ravno, ne obračaj se.",
  "100": "Vlěvo jest park, vpravo jest škola.",
  "101": "Odbočite vpravo pri crkvi.",
  "102": "Morje jest daleko od togo města.",
  "103": "Apteka jest blizko, pet minut hoda.",
  "104": "Škola jest naprotiv pošty.",
  "105": "Avtomobil potrěbuje benzin že by jehati.",
  "106": "Treba tankovati prěd dolgoju dragoju.",
  "107": "Telefon treba zarjažati každu noč.",
  "108": "Strahovanje povinno se kupiti prěd putovanjem.",
  "109": "Tvoj bagažnik jest uže polny.",
  "110": "Ne zabudi svoj bagaž v avtobusu.",
  "111": "Ja držu svoju torbu v rukě.",
  "112": "On je spakoval kufr prěd odjezdom.",
  "113": "Ona nese veliky rukzak na hrebetu.",
  "114": "V ktorom kraju jesi urodil se?",
  "115": "Na granici treba pokazati pasporty.",
  "116": "Graničny prěhod jest otvoreny.",
  "117": "Ja čekam povratok tvoj s radostju.",
  "118": "Kupil jesm bilet na vlak.",
  "119": "Avtobus stoji na postojkě deset minut.",
  "120": "Ne zabudi tvoju vhodnu kartu.",
  "121": "Let iz Pragi do Pariža trvaje dvě časiny.",
  "122": "Aerodrom jest daleko od grada.",

  "123": "On ne odhodi od svojego pisalnogo stola.",
  "124": "Usědi na stolku i čekaj.",
  "125": "Na rabotě u nas každy ima kompjuter.",
  "126": "Možeš tutčas bezpečno izključiti kompjuter. -- Windows 98",
  "127": "Tut jest prěglasno. Hodimo v konferencijnu salu.",
  "128": "Izgubil jesm ključ od doma.",
  "129": "Podaj nam svoje gaslo do banka. Musimo prověriti tvoje personalne dane. -- Kompjuterovy zločinec",
  "130": "Imam někaky problem s logovanjem.",
  "131": "Imaš li ty dostup k tomu fajlu?",
  "132": "Upravjanje projektami jest sbirka dějanij izpolnjanyh v cělju dosegnutja... -- Wikipedia",
  "133": "Ale ne tratite vrěme na tako nudno zadanje. -- Maly Princ",
  "134": "Napisal jesm o tom zapisku.",
  "135": "Termin za ten projekt jest v najblizšy petok.",
  "136": "Direktor firmy govori na sobranju. A ljudi muset to slušati.",
  "137": "Rukovoditelj odděla pomože ti najdti vlastnu osobu do togo zadanja.",
  "138": "Da by dostati kartu, potrěbuješ utvrdženja. Kto jest tvoj načelnik?",
  "139": "To jest Krištof Zelenina iz Ščetina. Šef vsih šefov. -- Utro kojota",
  "140": "Pracovnik sklada musi nositi rabotnu odědžu.",
  "141": "Prěd okolo dva tysečami lětami, osnoval jesm družinu rybakov. -- Tri směšky",
  "142": "Zaplata jest na koncu měseca.",
  "143": "On prosil o povyšenje zaplaty.",
  "144": "Po trěh godah ona je nakonec dostala avans.",
  "145": "Ona dobyla veliku premiju za poslědnju rabotu.",
  "146": "Najemny ubijca rabotaje bez dogovora.",
  "147": "Ona jest na odpusku do konca měseca.",
  "148": "Posle izvoljnjenja on išče novu rabotu.",
  "149": "Verbovanje novyh pracovnikov trvaje dolgo.",
  "150": "Obučenja pričisljajut se k rabotnomu vrěmenu. -- Poljsky rabotny kodeks",
  "151": "Ona ima bogate izkušenje v tej oblasti.",
  "152": "Koje sut tvoje dolžnosti v toj firmě?",
  "153": "Oddaljena rabota jest menje efektivna.",
  
  "154": "Firma oglasila bankrotstvo.",
  "155": "Ja jesm sovlastnik v kompanije s ograničenoju odgovornostju.",
  "156": "To veliko prědprijemstvo ima tyseče rabotnikov.",
  "157": "Uprava firmy je v Pragě.",
  "158": "Vlastnik togo doma jest bogaty.",
  "159": "Klient vsegda ima pravdu.",
  "160": "Dostavitelj bude prinesti produkty zautra.",
  "161": "Produkty sut v skladu za domom.",
  "162": "Prěstupili jeste budžet o dvadeset procent.",
  "163": "Dohod firmy raste každy god.",
  "164": "Naše razhody sut prěvelike.",
  "165": "Ničto ne jest isto kromě smrti i platb. -- Benjamin Franklin",
  "166": "Ja vam procenty ješče za měsec vnesu; potrpite. -- Prěstupanje i ukaranje",
  "167": "Odkogda je načel se razvoj, odtogda takože sut prišli problemy. -- Nehaj nas nesut...",
  "168": "Kompanija zapisala rast treti kvartal podred.",
  "169": "Nedostatok dělanij reklamovyh pričinil upadok rezultatov prodaži.",
  "170": "Naš uspěh jest rezultat dobrej raboty.",
  "171": "Tuta poražka nas naučila mnogo.",
  "172": "Bez rizika nema zabavy.",
  "173": "Naša kooperacija s tamtoju firmoju jest dobra.",
  "174": "Jedinstvo buduje, nesoglasje ruinuje.",
  "175": "Imamo silnu prěgovornu poziciju. Musimo to izkoristati.",
  "176": "Imam dlja njego propoziciju, ktoru on može odkloniti. -- Krestny Otec",
  "177": "On poslal nam prědloženje.",
  "178": "Treba tvoj podpis na tom dokumentu.",
  "179": "Tuto rěšenje jest konečno [ang. final].",
  
  "180": "Sladky aromat od ovsovyh kolačev razhodi se v kuhnji. -- Nehaj nas nesut...",
  "181": "V našej kupaljnji jest velika vanna.",
  "182": "Toalet jest v koridoru.",
  "183": "Ta komnata jest mala ale světla.",
  "184": "Otvori okno, prosim, da by vošlo něčto svěžego vozduha.",
  "185": "Ukončijte prosim vhodženje i izhodženje, dveri se zatvarjajut. -- Soobčenje v metru",
  "186": "Iz našego balkona vidimo cěly grad.",
  "187": "Podloga v kuhnji jest nečista. Prinesi utirak.",
  "188": "Stěna medžu tymi komnatami jest tonka.",
  "189": "Ni čestice praha ne možno bylo najdti v cěloj kvartirě. -- Prěstupanje i ukaranje",
  "190": "Segda možeš vratiti se do doma. -- Maly Princ",
  "191": "Toj budynok ima dvadeset etaže.",
  "192": "My živemo na tretim etažu.",
  "193": "Vozmi teleskop i běži na pokryv. -- Titus, Romek i A'tomek",
  "194": "Stupenišče do gornogo etaža jest kruto.",
  "195": "Idite po koridoru do konca.",
  "196": "V pivnici hranim vino.",
  "197": "Lift ne rabotaje, treba idti pěšo.",
  "198": "Naš sused jest mily stary muž.",
  "199": "Děti igrajut v sadě.",
  "200": "Najem za tu kvartiru jest vysoky.",
  
  "201": "Mlěko jest v hladilniku.",
  "202": "Nalij vodu v čajnik.",
  "203": "Hlěb pečem v peči.",
  "204": "Ona podgrěva jedanje v mikrovalnoj peči.",
  "205": "Naša kavovarka dela dobru kavu.",
  "206": "Toj grnec podhodi na indukcijsku plytu.",
  "207": "Daj mi ložicu, prosim.",
  "208": "Vzemi vidlicu so stola.",
  "209": "Nož jest ostry, budi ostražny.",
  "210": "Položi meso na talirku.",
  "211": "On pije vodu iz skljanky.",
  "212": "Ispij čaj iz čašky.",
  "213": "Soljnica jest prazna.",
  "214": "Izkydni smeti v koš odpadov.",
  
  "215": "Ona spi v maloj spaljnji na prvym etažu.",
  "216": "Ta poduška jest mekka.",
  "217": "Ručnik jest v kupaljnji.",
  "218": "Postelj jest široka. Možemo spati zajedno.",
  "219": "On leži na divanu i čitaje knigu.",
  "220": "Oni sědet za stolom i jedut.",
  "221": "Iztegni věči iz pralnoj mašiny. Pranje je dovršilo.",
  "222": "Ne zabudi izključiti gladilo kogda budeš dovršiti gladiti.",
  "223": "Mylo bude vse umyti, daže uši i šiju. -- Fasolki",
  "224": "Ona prijmaje duš každo jutro.",
  "225": "Vanna jest polna teploj vody.",
  "226": "Vključi lampu, jest temno.",
  "227": "Bystrost světla jest 300 tysečij km/s.",
  "228": "Prahososalnik jest v koridorě.",
  "229": "Vzemi metlu i podměti podlogu.",
  "230": "Vzemi utirak i utri stol.",
  
  "231": "Každy člověk potrěbuje ljubov.",
  "232": "Jedin iz mužev [..] hče utišiti děvčinu fragmentom vezala. -- Nehaj nas nesut...",
  "233": "Jej muž rabotaje v banku.",
  "234": "Ta žena govori tri jezyky.",
  "235": "Jej žena jest lěkar.",
  "236": "Koliko imaš děti? Koliko ja znaju, imam troje.",
  "237": "Dobry denj, gospodin Novak!",
  "238": "On jest uže dorastly čelověk. Nahaj sam rěšaje.",
  "239": "Ja jesm tvoj otec, Luke. -- Darth Vader",
  "240": "Moja mati vari oběd vsako denj.",
  "241": "Jej syn uči se v školě.",
  "242": "Tvoja dočera ne jest taka cělkom doskonala. -- Liroy",
  "243": "Moja babica proizhodi iz Chrzanowa. -- Stara reklama piva",
  "244": "Ja budu dokončiti, čto ty jesi načel, dědče. -- Kylo Ren",
  "245": "Ta rodina žive v velikom domu.",
  "246": "Čto děje se s ljubovoju poslě svatby?",
  "247": "Poslě razvoda ona žije sama.",
  "248": "Smrt jest naturalna čest žitja. -- Majstr Yoda",
  "249": "Na pogrebu byjo mnogo ljudij.",
  "250": "Toj hlapec igraje futbol na ulici.",
  "251": "Ta děvčina čita knigu v parku.",
  "252": "On jest moj najlěpši prijatelj.",
  "253": "Moja prijateljka žive v Pragě.",
  "254": "Moj kolega pomože mi s rabotoj.",
  "255": "Moja kolegica govori poljsky.",
  "256": "On jest moj znajemy iz raboty.",
  "257": "Imamo gosta na večerju.",
  "258": "Herojam slava!",
  "259": "Ne byti taki strahlivec! Každy někogda bude umrti.",
  "260": "Ne docěnili jesmo protnivnika.",
  "261": "On jest naš vrag v toj vojně.",
  "262": "Izigranje bude tvoja nagrada. Prědavstvo bude karane smrtju. -- Fragment prisegy Domorodnoj Armiji",
  "263": "Kaky to jest duren!",
  "264": "Ne budi idiot, mysli prěd govorenjem.",
  "265": "Zločinec izběgl prěd policijeju.",
  
  "266": "Jesi programist, tako napravi mi kompjuter. -- Tetka",
  "267": "Inženjer projektuje novy most.",
  "268": "Prihodi žena do lěkara s žaboju na glavě. - Něčto mi se do zadnice podključilo.",
  "269": "Medsestra bude pomogti pacientu.",
  "270": "Ne ljubim hoditi do zubnogo lěkara.",
  "271": "Vsi učitelje ljubet děti.",
  "272": "Policijnik bude pomogti nam najti dragu.",
  "273": "Vojak stoji prěd vhodom.",
  "274": "Naš šofer zna vse dragi.",
  "275": "Kelner bude prinesti nam jedivo.",
  "276": "Zloděj ukradl moju torbu.",
  "277": "Godite se byti buhhalterom. -- Monty Python",
  "278": "Kde jest šest kuharek, tam nema čto jesti.",
  "279": "Gorniki rabotajut pod zemjeju.",
  "280": "Frizer ostrigal moje vlasy krasno.",
  "281": "Sudja prěčital rěšenje.",
  "282": "Naš advokat pomagae nam.",
  "283": "Svečennik govori v crkvi.",
  "284": "Farmer ima mnogo zemlij.",
  "285": "Lovec ide v lěs rano jutro.",
  "286": "Prodavec pokazal nam novy produkt.",
  "287": "Sovětnik pomogl nam dobrym sovětom.",
  "288": "Prostitutka stoji na uglě ulicy.",
  "289": "Naš politik mnogo obečaje ale malo děla.",
  
  "290": "V lěsě živut dike životiny.",
  "291": "Ktory vid ptice jest to?",
  "292": "Sosaveci pijut mlěko materi.",
  "293": "On čuje se kako ryba v vodě.",
  "294": "Čul jesm, že srdce mu bije kako postrěljenoj, umirajučej ptici. -- Maly Princ",
  "295": "Komar jest insekt maly, ale bezpokoječi.",
  "296": "Dinozavry izmrěli šestdeset pet milionov godov nazad.",
  "297": "Naš pes ljubi begati po sadu.",
  "298": "Moj kot spi na divanie.",
  "299": "...v ogromnom vozu, zapregnutom ogromnym robočim konjem... -- Prěstupanje i ukaranje",
  "300": "Kravy ubivajut veče ljudij než akuly.",
  "301": "Myš izbegla v vugol.",
  "302": "Ščury prve opuščajut tonuči korab.",
  "303": "Lisica jest hytra.",
  "304": "Medvěd prospivaje cělu zimu.",
  "305": "Slon jest veliky i silny.",
  "306": "Krokodil žive v rěkě.",
  "307": "Žirafa ima dolgu šiju.",
  "308": "Malpa žive v tropičnom lěsu.",
  "309": "Tigr jest silna životina.",
  "310": "Lev jest kralj zvěrev.",
  "311": "Akula žive v morju.",
  "312": "Čto jest to: po vodě plyva i katka se nazyva?",
  "313": "Labudje jezero jest klasičny balet v četyrěh aktah.",
  "314": "Lěpši vrabec v rukě než golub na pokryvu.",
  "315": "Orel leti vysoko nad gorami.",
  "316": "Pingvin ne može lětati, ale može plavati.",
  "317": "Bočan prinosi ščestje.",
  "318": "Jastreb lovi myši.",
  "319": "Ne razuměm začto ljudi govoret do psov. -- Pověděl jesm do svojego papugaja",
  "320": "Trening jest ničto. Važna jest volja! Volja k dějanju. -- Člověk-netopyr",
  "321": "Zmija jest opasna životina. Može ukusiti ili udušiti.",
  "322": "Žaba skočila v vodu.",
  "323": "Črvjak žive v zemji.",
  "324": "Han, hlapče, razočaroval jesi mene. Začto jesi ne zaplatil? -- Polž Jabba",
  "325": "Ne ubivaj pavukov.",
  "326": "Dlja lovjenja komara potrěbno jest orudje - na priklad papuče.",
  "327": "Pčelka Maja sobě lěta, sbira nektar někde v cvětah. -- Akcent",
  "328": "Osa ima želo. Kogda ukolje, bude bolěti.",
  "329": "Krasny motylik leti od cvěta do cvěta.",
  
  "330": "Ja ne imam časa. Spěšim se.",
  "331": "Každy denj učim se něčto novo.",
  "332": "Noč byla temna i tiha.",
  "333": "Tydenj ima sedem dnjev.",
  "334": "Prosim bilety do kontroly! Prosim, měsečny. -- Titus, Romek i A'tomek",
  "335": "Želam ti ščastlivogo novogo roka.",
  "336": "To bude dnes večerom v sedmu časinu i četyrideset minut! - Maly Princ",
  "337": "Čekajte ješče pet minut.",
  "338": "Za sekundu vse se izměnilo.",
  "339": "Počekaj jednu hvilju.",
  "340": "V toj momentu ja ne znam čto rěkti.",
  "341": "Rano jutro jest moje ljubimo vrěme.",
  "342": "Duel bude odbyti se točno v poldenj.",
  "343": "Včera večerom jesmo sěděli v parku.",
  "344": "Včera ja byl jesm boljny. Dnes jesm uže zdravy.",
  "345": "Znaješ li, zautra minuje god odkud ja popadl jesm na Zemju... -- Maly Princ",
  "346": "Prošlost ne možeš izměniti.",
  "347": "Budučnost jest v naših rukah.",
  "348": "On izjel iz kěšenji stary, plosky, srěbny časovnik. -- Prěstupanje i ukaranje",
  "349": "V mojemm telefonu jest dobry kalendar.",
  "350": "Vlak jest zapozdněly dvadset minut. Za opozdnjenje izvinite. -- Poljske Krajeve Pojezdy",
  
  "351": "Daže vo Vronkah mene tak rano ne budili. -- Junoši ne plačut",
  "352": "Prišel jesm raněje než ty.",
  "353": "Prěsěči nebesky kabel... ale naprěd odključi... -- Instrukcija razoružanja bomby",
  "354": "Prěd obědom treba umyti ruky.",
  "355": "Poslě hvilje vračaje se i govori...",
  "356": "Lěpje pozdno než nikogda.",
  "357": "My budemo gotovi pozdněje.",
  "358": "Najprvo budemo pojdti za zakupkami, a potom budemo pojdti v restoran.",
  "359": "Někogda na Zemji žili dinozavry.",
  "360": "To bylo davno, uže ne pamětam.",
  "361": "Ona nedavno zaměnila rabotu.",
  "362": "Tutčas on ne jest v domu. Tutčas on je v rabotě.",
  "363": "Nyně v Poljskě žive se dobro.",
  "364": "Stava vse hladněje. Skoro bude prijdti zima.",
  "365": "Ne govori podčas jedanja.",
  "367": "Medžuvrěmenno ona naučila se novo slovo.",
  "368": "Bud tiho. On ješče spi.",
  "369": "Ty uže jedl?",
  "370": "On nikogda ne govori pravdu.",
  "371": "Ona rědko hoče pomogti.",
  "372": "Poněkogda idemo v restoran, ale obyčno jedamo v domu.",
  "373": "Časom hočel byh kydnuti vse i izjehati v Běščady.",
  "374": "Obyčno ne pijem čaj, ale dnes budem sdělati izključenje.",
  "375": "Ona často mene bezpokoji. Možemo li ju prěnesti v drugy ofis?",
  "376": "Vsegda myj ruky prěd jedivom.",
  "377": "Děte bezprěryvno plače.",
  "378": "Neustalo šumi mi v glavi.",
  "379": "Iznova jesmo probovali. I iznova ničto iz togo ne vyšlo.",
  "380": "Ne razuměm. Možeš li rěkti tuto slovo ponovno?",
  "381": "Budemo začeti nanovo od prvogo.",
  "382": "Naglo je zagrěmelo i načelo dožditi.",
  "383": "Daj mně znati kako toliko budeš prijehati.",
  "384": "- Kaky jest termin? - Čim raněje.",
  "385": "Dokolě ty jesi tu, ja budu s toboju.",
  "386": "Čekaj dopoka ne prijde.",
  "387": "On doprva několiko minut nazad skončil je rabotu.",
  "388": "Ona doprva v domu srazuměla tamtu směšku.",
  
  "389": "Jademo snědanje zajedno vsako jutro.",
  "390": "Oběd bude gotovy za pol časiny.",
  "391": "Na večerju imamo rybu.",
  "392": "Mně nravi se svěže ovoče.",
  "393": "Jedite zeleninu, ona polezna.",
  "394": "On ne jede meso.",
  "395": "Mlěko jest v hladilniku.",
  "396": "Kupite maslo v magazini.",
  "397": "Naš syr jest velje vkusny.",
  "398": "Kava s smetanoj jest myagka.",
  "399": "Šunka v sendviči jest vkusna.",
  "400": "Kura jest moje ljubimo jedivo.",
  "401": "Kartofelje varila jesm za oběd.",
  "402": "Děti ljubet pomfritky.",
  "403": "Ona kupila makarony v magazinu.",
  "404": "Ryž se kuha dvadset minut.",
  "405": "Na snědanje jademo kašu.",
  "406": "Salata jest svěža i krasna.",
  "407": "Naša kapusta raste v sadě.",
  "408": "Rěpa jest sladka i červena.",
  "409": "Mrkva jest oranževa i zdrava.",
  "410": "Pripravi supu iz mrkvy.",
  "411": "Ta podlivka jest velje ostra.",
  "412": "Pripravi salatu s oljejom.",
  "413": "Na deser budem jesti kolač.",
  "414": "Pijem čaj s mlekom.",
  "415": "Kava jest goryča.",
  "416": "On pije pivo s prijateli.",
  "417": "Červeno vino jest dobro s syrom.",
  "418": "Kupil jesm svěžu bulku.",
  "419": "Hlěb jest na stoli.",
  "420": "Mama spekla kolač za jutro.",
  "421": "On ne jede glutena.",
  "422": "Svinina jest na trelice.",
  "423": "Govedina jest v supi.",
  "424": "Jajca sut na talirki.",
  "425": "Děti ljubet sladkosti.",
  "426": "Fasolja jest v supi.",
  "427": "Grah jest zeleny i sladky.",
  "428": "Paprika jest oranževa i krasna.",
  "429": "Cibulja jest ostra.",
  "430": "Česnok ima silny vonj.",
  "431": "Orěh jest tvrd.",
  "432": "Jabloky rastu na drěvě.",
  "433": "Gruša jest sladka i myagka.",
  "434": "Jagody sut červeny i vkusny.",
  "435": "Sliva jest modra i sladka.",
  "436": "Banan jest žolty i sladky.",
  "437": "Ananas raste v toplom kraju.",
  "438": "Grozdje jest sladko.",
  "439": "Pomaranča jest oranževa.",
  "440": "Limon jest kisely.",
  "441": "Drži ruky v kěšenjah i svistaje. -- Titus, Romek i A'tomek",
  "442": "On podal mi dlanj na pozdravljenje.",
  "443": "Ona je lomila nogu prěd tremi lětami.",
  "444": "Glava me boli.",
  "445": "Ona ima krasno lice.",
  "446": "Vse v rukah člověka i vse to on mimo nosa propušča. -- Prěstupanje i ukaranje",
  "447": "Ona ne slyšit dobro levym uhom.",
  "448": "Jej oko jest sinje.",
  "449": "Zrěnje mu jest slabo.",
  "450": "Zub mě boli, treba idti k lěkaru.",
  "451": "Boli mě brjuho posle jediva.",
  "452": "Boli mě hrebet posle dolgoj raboty.",
  "453": "Ona ima dluge vlasy.",
  "454": "Moj jezyk ne može togo rěkti.",
  "455": "Boli mě prst.",
  "456": "Ona maljuje svoji nogty.",
  "457": "Pasti na zadnicu jest směšno.",
  "458": "Koleno boli posle bega.",
  "459": "Stopa boli od dolgoj hody.",
  "460": "Lěkar kazal, čto kost jest prelomjena.",
  "461": "Krov jest vidna na rani.",
  "462": "Vena jest vidna na rukě.",
  "463": "S zamirajučim srdcem i nervoznym drženjem podšel on k ogromnomu domu. -- Prěstupanje i ukaranje",
  "464": "Moj želudok boli.",
  "465": "Jetra jest važny organ.",
  "466": "Pljuča potrěbujut čist vozduh.",
  "467": "Črěvo boli po jedivě.",
  "468": "Ta věč jest moja.",
  "469": "Ona kupila novo oblěčenje.",
  "470": "Moje obuvky sut mokre.",
  "471": "Šapka ta byla vysoka, krugla, zimmermanovska... -- Prěstupanje i ukaranje",
  "472": "On oblěkl plašč i išel von.",
  "473": "Ta košulja jest sinja.",
  "474": "Moje nogavice sut mokre.",
  "475": "On nosi sako na rabotu.",
  "476": "Žilet jest pod sakom.",
  "477": "Ona ima krasnu suknju.",
  "478": "Na svadbu on nosil klasičny kostjum.",
  "479": "On nosi naočila dlja čitanja.",
  "480": "Vzemi doždnik, bude dožd.",
  "481": "Tvoje rukavice sut pod stolom.",
  "482": "Škarpetki sut v kufri.",
  "483": "Gače sut v pranje.",
  "484": "Ona kupila nove stringi.",
  "485": "On spavaje v pižami.",
  "486": "Jeduči na velosipedu, nosim šlěm.",
  "487": "Kosmetika jest v maloj torbi.",
  "488": "Ten krem jest dobry za ruce.",
  "489": "Dezodorant jest v kupaljnji.",
  "490": "On vzal zapalničku i razžeg svěčku.",
  "491": "Vsegda beri prezervativ.",
  "492": "Lěkar vzal špric.",
  "493": "Vzemi nožice i ostriži.",
  "494": "Ona nosi lyže v gorach.",
  "495": "Děti jezdet na slizajkah po ledu.",
  "496": "On jezdi na roljkah v parku.",
  "497": "Daj mi kruglu!",
  "498": "Vitez nosi meče.",
  "499": "Vojak drži ščit.",
  "500": "Oružje jest opasno.",
  "501": "On daroval jej krasny prstenj.",
  "502": "Ona nosi zlaty nagrdelnik.",
  "503": "Moj dar tebě jest ta kniga.",
  "504": "Pijte mnogo vody každy denj.",
  "505": "Morje jest sinje i temno.",
  "506": "Okean jest prěveliky.",
  "507": "Jezero jest blizko gory.",
  "508": "Rěka teče prěz lěs.",
  "509": "My idemo na plaž jutro.",
  "510": "Děti igrajut na pěsku.",
  "511": "Na tom ostrovu žive malo ludej.",
  "512": "Korab jest v zatoki.",
  "513": "Kanal prěz to město jest stary.",
  "514": "V pustynji jest velě žarko.",
  "515": "Spali jesmo pod golym nebom.",
  "516": "Noču vidno mnogo zvězd.",
  "517": "Idemo v gory na vikend.",
  "518": "Ta skala jest visoka i opasna.",
  "519": "V lěsě jest tiho i mirno.",
  "520": "Drěvo raste prěd našim domom.",
  "521": "Kust raste pri plotu.",
  "522": "Zeleny list padl na zemju.",
  "523": "Korenj togo drěva jest veliky.",
  "524": "Větka s cvěty jest krasna.",
  "525": "Trava jest zelena i myagka.",
  "526": "Krava pase se na poljaně.",
  "527": "Cvět raste v sadě.",
  "528": "V lěsě nahodiš mnogo gribov.",
  "529": "Na polju rastut žita.",
  "530": "Bagno jest opasno za hodžu.",
  "531": "Zima hladno, oblěci se teplo.",
  "532": "Jutro jest teplo i solnečno.",
  "533": "Mraz ščipje lice.",
  "534": "V avguste byva velika gorečnja.",
  "535": "Solnce sijaje každy denj v lětě.",
  "536": "Dožd padaje iz oblakov.",
  "537": "Děti ljubet igrati v sněgu.",
  "538": "Led na rěkě jest tonky.",
  "539": "Burja razrušila nješkoliko domov.",
  "540": "Oblak zakryl solnce.",
  "541": "Děti bavet se na svěžem vozduhu.",
  "542": "Větr otvoril okno.",
  "543": "Naš grad jest veliky i krasny.",
  "544": "To jest krasno město na gori.",
  "545": "Kupil jesm hlěb v magazinĕ.",
  "546": "Provodi mladca črěz ulicu. -- Titus, Romek i A'tomek",
  "547": "Děti idut do školy každy denj.",
  "548": "Crkva jest stara i krasna.",
  "549": "Parkovišče jest za budynkom.",
  "550": "Restoran na uglě jest dobry.",
  "551": "On byl prevežen do boljnice.",
  "552": "Vlak odhodit od stancije.",
  "553": "Naša platforma jest devjata.",
  "554": "Most prěz rěku jest visok.",
  "555": "Ogonj v lěsě jest opasny.",
  "556": "Ne iměl jesm dost grošev.",
  "557": "Cěna togo avta jest visoka.",
  "558": "Prinesite mi rahunok, prosim.",
  "559": "Ostavi napojnicu kellnerovi.",
  "560": "Platim kartoju, ne gotovinom.",
  "561": "Hotěl byh kupiti novu knigu.",
  "562": "On prodal svoj avto.",
  "563": "Izgleda, že jedino ja budem platiti vnosy. -- Titus, Romek i A'tomek",
  "564": "Zaplatil jesm za oběd.",
  "565": "Koliko koštuje ta suknja?",
  "566": "Zloděj ukral moj telefon.",
  "567": "V tom magazinĕ vsě prodajut deševo.",
  "568": "To avto jest prědrago dlja mene.",
  "569": "Platil jesm gotovinom.",
  "570": "Plati pri kasě.",
  "571": "V petok jest razprodaž v magazini.",
  "572": "Na tom sajtě byva obniženje cěn.",
  "573": "On dal nam veliky rabat.",
  "574": "Kava s soboju, prosim.",
  "575": "Rěci mi pravdu.",
  "576": "Ne govori lži.",
  "577": "Dostatočno, že odgovoriš sobě na jedno važne pytanje: Čto ljubju v žitju dělati?"
  "578": "Ona ne dala mi odpověd.",
  "579": "Imamo veliky problem s projektom.",
  "580": "Nahodimo rěšenje zajedno.",
  "581": "To byja moja pogrěška.",
  "582": "Ona sdělala grěšku.",
  "583": "V tom programu jest hyba.",
  "584": "Avto ima defekt.",
  "585": "Oprava steny bude stojati drago.",
  "586": "Imali jesmo dolgy razgovor.",
  "587": "Vsi idut na zabavu.",
  "588": "Imali jesmo razprju o toj temě.",
  "589": "Sustrěča jest v srědu.",
  "590": "To byjo važno sobytje.",
  "591": "Toj slučaj jest poučny.",
  "592": "Neščestny slučaj na dragi byl rano jutro.",
  "593": "Vojna jest strašna věč.",
  "594": "Vsegda hočem žiti v pokoji.",
  "595": "On ljubi svoju rabotu.",
  "596": "Učenje językov jest zabavno.",
  "597": "Ona ima znanje medžuslovjanskogo.",
  "598": "Nu, zatom načinamo praktikovanja. -- Titus, Romek i A'tomek",
  "599": "Moje mněnje jest razno.",
  "600": "I o to idě, trěba sbirati silne vraženja. -- Junoši ne plačut",
  "601": "Na vakaciju jademo k morju.",
  "602": "Toj zakon naredžaje platiti.",
  "603": "Imam dobru ideju!",
  "604": "Kako to jest dobry sposob?",
  "605": "Jej naměr byl pomoči nam.",
  "606": "On ima ostry razum.",
  "607": "Buduči astronavt musi zadržati trězvost uma v každoj situaciji. -- Titus, Romek i A'tomek",
  "608": "Kakoě jest značenje togo slova?",
  "609": "Svoboda jest dragocěna.",
  "610": "Jest možnost pomogti?",
  "611": "Ih svezok jest silny.",
  "612": "Uslovje jest prosto.",
  "613": "Koliko čislo jest tu?",
  "614": "Kakova jest kolikost?",
  "615": "Kakost togo produkta jest visoka.",
  "616": "Točnost jest važna v toj rabotě.",
  "617": "Osnova projekta jest dobra.",
  "618": "Na početku bylo težko.",
  "619": "My jesmo na koncu toj dragi.",
  "620": "Nedostatok vody jest problem.",
  "621": "Ona ima alergiju na pticu.",
  "622": "Zdravje jest najvažněja věč.",
  "623": "Hvoroba prišla naglo.",
  "624": "Kakova jest srědina?",
  "625": "Budem gledati z obih stran.",
  "626": "To jest mala čest našego plana.",
  "627": "Vzeli jesmo cělost togo problemu.",
  "628": "Dviženje togo avta bystro.",
  "629": "Jej glas jest myagky i krasny.",
  "630": "Zvuk muzyky jest glasny.",
  "631": "Muzika nas veseli.",
  "632": "Jego izgled jest krasny.",
  "633": "Vonj cvětov jest krasna.",
  "634": "Pogled na morje jest prěkrasny.",
  "635": "Njegova ljubov k njej jest silna.",
  "636": "Radost děcej razveselit vsih.",
  "637": "Ščestje jest v malyh věčah.",
  "638": "Smutok prišel posle poměšanja.",
  "639": "Slyšim plač děteta.",
  "640": "Strah ne pomaže, treba dějati.",
  "641": "Bezpokojstvo jest lišno.",
  "642": "Bolj v ruci jest silna.",
  "643": "Jej nastroj se izměnil naglo.",
  "644": "Muzika mi daje prijemnost.",
  "645": "Bezpečnost děcej jest važna.",
  "646": "Dověrje gradi silne svezki.",
  "647": "Naš dobry sused vsegda pomaga.",
  "648": "Ta lěpša metoda pomaga.",
  "649": "To jest najlěpša kniga ktoru čital jesm.",
  "650": "Zly čas prošel, vsě bude dobro.",
  "651": "Situacija byja gorša nego myslil jesm.",
  "652": "To byl najgroši denj mojego žitja.",
  "653": "Oni živut v velikom domu.",
  "654": "To děte jest malo i krasno.",
  "655": "Srědnja cěna jest dobra.",
  "656": "Ta gora jest vysoka.",
  "657": "On govori tiho i nizko.",
  "658": "Ta draga jest dolga.",
  "659": "Věčer jest kratky.",
  "660": "Ona ima krasno lice.",
  "661": "Ten muž jest bridky i nekrasny.",
  "662": "Bystry avto pojehal prěz most.",
  "663": "Medla čerepaha hodi po poljaně.",
  "664": "Ta matematika jest trudna dlja mene.",
  "665": "Toj kamjon jest velje težky.",
  "666": "Ta zadača jest legka.",
  "667": "Legky rukzak jest lěpši dlja putovanja.",
  "668": "Naša kuhnja jest vsegda čista.",
  "669": "Nečisty stol treba umyti.",
  "670": "Ta draga jest nebezpečna noću.",
  "671": "To jest važna věč, ne zapominajte.",
  "672": "Medžuslovjansky jest zajmlivy język.",
  "673": "Ta kniga jest nudna.",
  "674": "- pomyslil on so strannym usměhom. -- Prěstupanje i ukaranje",
  "675": "Ta situacija jest směšna.",
  "676": "Ona kupila novy kompjuter.",
  "677": "To jest moja prva rabota.",
  "678": "Ona jest drugy raz zamužem.",
  "679": "To jest moja poslědnja šansa.",
  "680": "V poprědnjem godě vsě bylo ino.",
  "681": "Nastupny vlak bude za hodinu.",
  "682": "Iny sposob jest lěpši.",
  "683": "To jest različny produkt.",
  "684": "V tom magazini sut različne veci.",
  "685": "Imamo raznorodne ideje.",
  "686": "Toj dom jest podobny k našemu.",
  "687": "My živemo v jednakom domu.",
  "688": "On mysli inako než ja.",
  "689": "Avto jest poškodženo.",
  "690": "Moja torba jest polna.",
  "691": "Stakan jest pusty.",
  "692": "On jest zajety vse vrěme.",
  "693": "Vaš soběd jest potrěbny.",
  "694": "To jest nužno dlja tvojego zdravja.",
  "695": "Voda jest neobhodima dlja žitja.",
  "696": "Pasport jest obvezny dlja putovanja.",
  "697": "On byl dolžny vokrug gospodynji i bojal se s njeju strěsti. -- Prěstupanje i ukaranje",
  "698": "Ten soběd jest koristny.",
  "699": "Ta stolka jest vygodna.",
  "700": "To jest prigodna opcija.",
  "701": "To jest uměstny odgovor.",
  "702": "Něčto se stalo. Pogledatelj ne odgovorja. -- Titus, Romek i A'tomek",
  "703": "To jest umětny material.",
  "704": "Toj park jest obča věč.",
  "705": "On govori čudžim językom.",
  "706": "Ona jest ščestliva s novoju rabotoju.",
  "707": "On jest rad s rěšenjem.",
  "708": "Ona jest smutna posle rozluki.",
  "709": "On byl udivjeny podarkom.",
  "710": "Vse byli udivjeni toj věstoju.",
  "711": "On byl prěstrašeny glasnym zvonom.",
  "712": "On jest srdity na nas.",
  "713": "Ona jest smučena situacijom.",
  "714": "Děte jest bezpokojno nochu.",
  "715": "On jest razdraženy moim pytanjem.",
  "716": "Ona jest gorda na svojego syna.",
  "717": "On jest nesmělivy na novom místě.",
  "718": "Dodava sobě hrabrosti. -- Titus, Romek i A'tomek",
  "719": "Bědna rodina potrěbuje pomoč.",
  "720": "Bogaty muž žive v velikom domu.",
  "721": "On jest nepodatlivy i ne slušaje.",
  "722": "Posle dolgoj dragi ja jesm utomljeny.",
  "723": "Ta rabota jest umarjajuča.",
  "724": "Posle maratona on byl umorjeny.",
  "725": "Ona jest mila i pomaga vsim.",
  "726": "On jest čestny muž.",
  "727": "On jest zdravy i silny.",
  "728": "Boljny muž leži v posteli.",
  "729": "Stary dom treba renovirati.",
  "730": "Mlady muž běži bystro.",
  "731": "Silny muž nosi těžky kamen.",
  "732": "Slaby zvuk z daleka.",
  
  "733": "A ja imam svoju gitaru.",
  "734": "Toj veb-sajt ne istnuje. -- Grěška 404",
  "735": "Ona umě govoriti na peti jezykah.",
  "736": "Vsaky ne-neobhodimy personal može idti do doma raněje. -- Dilbert",
  "737": "On smogl dokončiti rabotu v čas.",
  "738": "Projekt nam udal se.",
  "739": "Ona uspěla v novoj firmě.",
  "740": "My uspěli priti v čas.",
  "741": "Musěti zaplatiti za vsě.",
  "742": "Ty povinen pomogti im.",
  "743": "Potrěbujemo novogo kompjutera.",
  "744": "Ona ljubit čitati knigy.",
  "745": "On ljubit svoju ženu i děti.",
  "746": "Imaju naděju viděti tebe skoro.",
  "747": "On žije v Prazi uže pjet lět.",
  "748": "Ona žije i ljubit každy denj.",
  "749": "Čto značit to slovo?",
  "750": "Ta kniga prinaleži knjižnici.",
  "751": "To tyče se tebe i mene.",
  "752": "Čto ty dělaješ tutčas?",
  "753": "Ona sdělala dobro delo.",
  "754": "Avto dviže se bystro.",
  "755": "Drži knigu v obih rukah.",
  "756": "Zadržite avto!",
  "757": "On shvatil loptu.",
  "758": "Kamo ty ideš?",
  "759": "Ona prišla domov pozdno.",
  "760": "Ona prihodit každy denj v šest.",
  "761": "On běži bystro prěz park.",
  "762": "Ona běgaje každo jutro v parku.",
  "763": "Jehali jesmo do morja s rodinoju.",
  "764": "Vlak prijede v tri.",
  "765": "Ptice letut na jug na zimu.",
  "766": "Naš let priletěl v čas.",
  "767": "Ona plyve v jezeru.",
  "768": "Korab plove po morju.",
  "769": "On plavaje každo jutro.",
  "770": "Prinositi kavu každo jutro.",
  "771": "Ona prinesla nam hlěb.",
  "772": "Prěnesti knigy do inoj komnaty.",
  "773": "On vozdvignul těžky kamen.",
  "774": "Kydnut loptu visoko.",
  "775": "Ona stoji prěd školoju.",
  "776": "Vstani rano i pripravi se.",
  "777": "...lěpje proslizgnuti se kako-nebud i izběgnuti, da by nikto ne viděl. -- Prěstupanje i ukaranje",
  "778": "Tegnuti za konec vrvi.",
  "779": "Ona skočila prěko potoka.",
  "780": "Oni tancujut na věčerě.",
  "781": "On pěvaje krasno.",
  "782": "Děti igrajut v sadu.",
  "783": "Naša komanda izigrala!",
  "784": "On proigral v šahah.",
  "785": "Obježdžali jesmo staro město.",
  "786": "Čekajte mene, skoro pridu.",
  "787": "On govori medžuslovjansky dobro.",
  "788": "Skaži mi pravdu.",
  "789": "On kazal vsim tiho stati.",
  "790": "Pytala jesm lěkara o lěčenju.",
  "791": "Zapytala jesm o dragě.",
  "792": "On pomagaje nam vsegda.",
  "793": "Ona pomogla mi s zadanjom.",
  "794": "On izbavil děte od opasnosti.",
  "795": "On pozvaljaje nam priti.",
  "796": "Šef pozvolil nam oditi raněje.",
  "797": "Strětli jesmo se v parku.",
  "798": "On žartovaje vsegda.",
  "799": "Ona zvonit mi každy denj.",
  "800": "Pozvonil jesm prijatelju.",
  "801": "Šef pobudžajet rabotnikov.",
  "802": "Ne mogu ubědžati go.",
  "803": "Ona hvali rabotu svogo syna.",
  "804": "Kritikovati bez razuma jest liho.",
  "805": "Ona nagradila dobrego rabotnika.",
  "806": "On byl pokarany za tu grěšku.",
  "807": "Firma dala rabotu sto novym ludjem.",
  "808": "On byl izvoljněny posle roka.",
  "809": "Ona davaje mi knigy každy měsec.",
  "810": "Daj mi to, prosim.",
  "811": "On bere knigu z stola.",
  "812": "Vzmi knigu i čitaj.",
  "813": "On dostavaje poslanija každy denj.",
  "814": "Pozajel jesm knigu od prijatelja.",
  "815": "Dati zajem pěnezy prijatelju.",
  "816": "Vojaci bojevahu za svobodu.",
  "817": "Ja věrju tebě.",
  "818": "Čuju tvoj glas.",
  "819": "Ne dotykaj se togo!",
  "820": "Viděl jesm tebe včera.",
  "821": "Uviděl jesm krasny cvět.",
  "822": "Gledaj na nebo.",
  "823": "Pozri na totu knigu.",
  "824": "Obdivjaju krasotu toj gory.",
  "825": "Slyšu muziku iz ulice.",
  "826": "Slušajte učitelja.",
  "827": "Uslyšal jesm glas iz daleka.",
  "828": "Pas njuhaje vsje.",
  "829": "Oni jedut za stolom.",
  "830": "Sjela jesm vsě pirogy.",
  "831": "Pijem vodu každy denj.",
  "832": "Napil jesm se mlěka.",
  "833": "Izpi tu kavu.",
  "834": "Ona spi do devjet časin.",
  "835": "Zasnu bystro posle trudnogo dnja.",
  "836": "On ubil zmiju v sadě.",
  "837": "Stary pes umrl minulo lěto.",
  "838": "Lěkar lěčit bolnogo.",
  "839": "Odpočivati posle raboty jest važno.",
  "840": "Ona cělovaje děte na dobru noč.",
  "841": "On rabotaje v toj firmi deset lět.",
  "842": "Ona zarabotyvajet dobry hlěb.",
  "843": "On myslit o novom projektu.",
  "844": "Ona izmyslila novy sposob.",
  "845": "Razuměju te dobro.",
  "846": "On srazuměl situaciju.",
  "847": "Poznala jesm novu kolegicu.",
  "848": "Učim se medžuslovjansky každy denj.",
  "849": "Naučil jesm se novo slovo.",
  "850": "Ona studiujet medicinu v universitětě.",
  "851": "Iz togo izveli jesmo zaključok.",
  "852": "Izobrazite si lěpše žitje.",
  "853": "On izměnil mněnje posle razgovora.",
  "854": "Ona pametaje vsě dnej.",
  "855": "Ne zabyti knigu doma.",
  "856": "Pripoměni mi o tom.",
  "857": "Pomylil jesm se v tom voprosi.",
  "858": "On naměruje otiti jutro.",
  "859": "Izdava se, čto ona ne jest doma.",
  "869": "Prověri, či prišel poslanije.",
  "870": "Treba prěgleděti vsě dokumenty.",
  "871": "Lěkar raziskal pacienta.",
  "872": "Ocěni situaciju prěd dějanjem.",
  "873": "Izbirajem meju dvěma opcijama.",
  "874": "Ona izbrala novu rabotu.",
  "875": "On čitaje knigu každu večerju.",
  "876": "Pročitala jesm vsju tu knigu.",
  "877": "Ona piše pismo prijatelju.",
  "878": "Napiši mi svoj adres.",
  "879": "Izgubil jesm svoj pasport.",
  "880": "To ne sut roboty ktoryh vy iščete. -- Obi-Wan Kenobi",
  "881": "Najde knigu na stolu.",
  "882": "Myjem ruky prěd jedivom.",
  "883": "Umyi lice prěd odhodom.",
  "884": "Otvarjati okno rědko.",
  "885": "Otvori dveri, prosim.",
  "886": "Zatvarjati okna noču.",
  "887": "Zatvorila jesm vrata na ključ.",
  "888": "Pokaži mi dragu na karti.",
  "889": "Ukryi knigu pod stolom.",
  "890": "Shovaj moj dar do jego prihoda.",
  "891": "Odstrani vsje stare dokumenty.",
  "892": "Podkjuči kompjuter k sěti.",
  "893": "Pridaj solji v supu.",
  "894": "On popravil avto.",
  "895": "Izniščiti stary mebel.",
  "896": "Izměni bateriju v časovniku.",
  "897": "Izpolni formuljar svojimy danymi.",
  "898": "On začinaje novy projekt jutro.",
  "899": "Začeti govoriti o problemu.",
  "900": "Ona končajet rabotu v šest.",
  "901": "On skončil pismo.",
  "902": "Pojezdka trvaje tri časiny.",
  "903": "Probuj opet!",
  "904": "Povtarjajte slova každy denj.",
  "905": "Povtori odgovor gromko.",
  "906": "On ostaje v domu tutčas.",
  "907": "Ona stala lěkarom.",
  "908": "Prihodi s mnoju.",
  "909": "On prišel bez torby.",
  "910": "Vsi prihodet kromě Marka.",
  "911": "Pomimo dožda, idemo von.",
  "912": "Vzemi moju knigu vměsto tvojej.",
  "913": "Pod stolom leži pas.",
  "914": "Ptica leti nad domom.",
  "915": "Avto stoji pred vhodom.",
  "916": "Ona sedi za domom.",
  "917": "Škola jest medžu parkom i rěkoju.",
  "918": "On stoji pri okni.",
  "919": "Apteka jest podle naše školy.",
  "920": "Kniga leži na stolu.",
  "921": "Živi v malom domu v lěsě.",
  "922": "Voda tečet iz rěky.",
  "923": "Pismo od mamy prišlo.",
  "924": "Čekamo do trěh časin.",
  "925": "Idemo k prijatelju.",
  "926": "Lěpi vodu v čašku.",
  "927": "Ten dar jest dlja tebe.",
  "928": "Ta suknja jest za večerju.",
  "929": "Za tri dny vrnemo se.",
  "930": "Vsě sut protiv togo plana.",
  "931": "Čto jest vnutri tej torby?",
  "932": "Vně jest hladno.",
  "933": "Idemo črěz park.",
  "934": "Vsečto jest gotovo.",
  "935": "Vsi prihodet na večerju.",
  "936": "Někto ključaje na dveri.",
  "937": "Hočeš něčto rěkti?",
  "938": "Čtokoli rěkneš, ja slušaju.",
  "939": "Čto-nebud kupiti nam.",
  "940": "Někaky muž pytajet te.",
  "941": "Kniga jest někde v toj komnate.",
  "942": "To jest něčij telefon.",
  "943": "On odhodi někamo každy večer.",
  "944": "Budem někako rěšiti ten problem.",
  "945": "Idemo někudy prěz lěs.",
  "946": "Něčemu on ne prišel.",
  "947": "Kojkoli den jest dobry dlja raboty.",
  "948": "Vse ravno, gde jemo.",
  "949": "Na priměr, možeš rěkti 'dobry denj'.",
  "950": "On govorit dobro, čto vyše, on piše krasno.",
  "951": "Imenno to imaju v mysli.",
  "952": "Každy muž ima svoju dragu.",
  "953": "Žaden iz ih ne priide.",
  "954": "Oba brata priidu jutro.",
  "955": "Idemo zajedno v park.",
  "956": "Oni živut oddělno.",
  "957": "Točno to imaju v mysli.",
  "958": "On ne rěke ničto.",
  "959": "Nikto ne znaet toj tajny.",
  "960": "Ona nikogda ne zapozdňaje.",
  "961": "Nikde ne nahodim toj knigy.",
  "962": "On zna vsede vsih.",
  "963": "Črvena roža jest moja ljubima.",
  "964": "Trava jest zelena v lětě.",
  "965": "Nebo jest modro.",
  "966": "Moj avto jest črny.",
  "967": "Ona nosi bělu suknju.",
  "968": "Solnce jest žolte.",
  "969": "On kupil oranževo jabloko.",
  "970": "Ona ima rozovu košulju.",
  "971": "Fioletovy cvět jest krasny.",
  "972": "Medvěd jest koričnevy.",
  "973": "Nebe jest sěro i oblačno.",
  "974": "On ima zlate vlasy.",
  "975": "Ona nosi srěbrny prstenj.",
  "976": "V ponedělok imam važnu sustrěču.",
  "977": "Vtorok jest trudny denj.",
  "978": "V srědu imamo sustrěču.",
  "979": "V četvrtok prihodit naš klient.",
  "980": "V petok vsě radujut se.",
  "981": "V subotu idemo v gory.",
  "982": "Nedělja jest denj odpočinoka.",
  "983": "Januar jest najhladněji měsec goda.",
  "984": "Fevruar jest kratky měsec.",
  "985": "V mareci sněg taje.",
  "986": "V aprilu cvěte sad.",
  "987": "V maju vsje zeleno.",
  "988": "Junij jest teplo a solnečno.",
  "989": "V juliju idemo na plaž.",
  "990": "Avgust jest najgorěči měsec.",
  "991": "V septembri děti idut v školu.",
  "992": "V oktobrě listi padajut.",
  "993": "V novembri jest hladno i sěro.",
  "994": "Dekembr jest měsec darkov.",
  "995": "Vesna jest moje ljubimo vrěme goda.",
  "996": "V lětě idemo k morju.",
  "997": "Jesenj jest krasna s červenymi listami.",
  "998": "Zimoju pada sněg.",
  "999": "Město jest na sěverě zemje.",
  "1000": "Naš grad jest na jugu.",
  "1001": "Solnce vshodi na vozhodi.",
  "1002": "Větr prišel z zapada.",
  "1003": "Možno jest da prideš jutro?",
  "1004": "To jest nemožno.",
  "1005": "Malo pravdopodobno jest, čto on bude prijdti.",
  "1006": "Može, ona bude pridti po obědi.",
  "1007": "Věrojetno on zabyl.",
  "1008": "Pravdopodobno ona jest doma.",
  "1009": "Uvěrjeno budu pridti jutro.",
  "1010": "Isto, ona znajet otgovor.",
  "1011": "Nesumněno, to jest pravda.",
  "1012": "Izdava se, že on ne razuměet.",
  "1013": "On i ja idemo zajedno.",
  "1014": "Kava ili čaj?",
  "1015": "Ja rabotaju, a ona učit se.",
  "1016": "On govorit a takože piše dobro.",
  "1017": "Ili ty ideš, ili ja.",
  "1018": "Ni on ni ona ne pridet.",
  "1019": "On hotěl priti, ale byl boljny.",
  "1020": "Ona jest starěja než ja.",
  "1021": "Myslim, že on pridet.",
  "1022": "On byl boljny, tako ne prišel.",
  "1023": "Govori glasno, tako že vsě slysjet.",
  "1024": "On byl slaby, zatom ne prišel.",
  "1025": "Prišla aby pomogti.",
  "1026": "Prosim da by on prišel.",
  "1027": "Hot on by byl boljny, prišel.",
  "1028": "Ne prišel, tomu že byl boljny.",
  "1029": "Ne prišel, ibo byl jesm boljny.",
  "1030": "Ne prišel po pričině bolezny.",
  "1031": "Vslěd neplačenija, ugovor byl rastorgnut.",
  "1032": "Hvala tebě, smogla pomogti.",
  "1033": "Tomu on prišel sam.",
  "1034": "Radi zdravja treba spati dobro.",
  "1035": "Zaradi firmy, on rabotajet dvadset četyre hodin.",
  "1036": "Soglasno pravilam, vsě treba platiti.",
  "1037": "Podolg novosti, on uže jest doma.",
  "1038": "Ako prideš, javi se.",
  "1039": "Ne pridu, ako ne pozvoniš.",
  "1040": "Ne znam, či on bude prijdti.",
  "1041": "On hotěl prijdti, jednako ne mogl.",
  "1042": "Daže děti razumejut to.",
  "1043": "Bylo tak těžko, až plakala.",
  "1044": "Jedino ty možeš pomogti mi.",
  "1045": "Govorit kako by on by byl boljny.",
  "1046": "On takože govorit po-russky.",
  "1047": "V parku bylo mnogo ludej.",
  "1048": "Kupili jesmo mnogo jediva.",
  "1049": "Bylo velmi mnogo dožda.",
  "1050": "Nemnogo knig ostalo.",
  "1051": "Imam nekoliko pytanj.",
  "1052": "Malo mlěka jest v skljanki.",
  "1053": "Bylo velmi malo vrěmeny.",
  "1054": "Ona jest velmi mila.",
  "1055": "Hočem vyše kavy.",
  "1056": "To jest najvyše čto možemo dati.",
  "1057": "Ta gora jest vyša než tamta.",
  "1058": "On čita vse bolje.",
  "1059": "Daj mi veče soli.",
  "1060": "Imam menje vrěmeny.",
  "1061": "Prišlo menje ludej nego čekali jesmo.",
  "1062": "Najmenje čto možeš sdělati.",
  "1063": "On žive niže v dolině.",
  "1064": "Větr dul silno.",
  "1065": "On bije avto močno.",
  "1066": "Svěča gorěla slabo.",
  "1067": "Daj mi trohu soli.",
  "1068": "Ne piju prěmnogo alkohola.",
  "1069": "On bliz zabyl.",
  "1070": "Byl jednoraz v Parizi.",
  "1071": "Posetil jesm Pragu dvukratno.",
  "1072": "On jedva pridet v čas.",
  "1073": "Zadanje jest dost prosto.",
  "1074": "Sovšem ne razuměm.",
  "1075": "On vzal pol kolača.",
  "1076": "On sjel cěly kolač.",
  "1077": "Na žalost, on ne prišel.",
  "1078": "To napravdu jest divno.",
  "1079": "Vse jest v poredku.",
  "1080": "Jedno uslovje jest nužno.",
  "1081": "Dodaj cukr v čaj.",
  "1082": "Moji roditelji živut v malom selu.",
  "1083": "Byli jesmo na ekskursiji v Pragě.",
  "1084": "On žive v malom selu.",
  "1085": "Věd ty znaješ odgovor!",
  "1086": "Ten soběd mi prigodil se.",
  "1087": "Ne nepokoji se, vsě bude dobro.",
  "1088": "Ne bezpokoj mene!",
  "1089": "Prišla mi vědomost od prijatelja.",
  "1090": "Najvažny punkt jest treti.",
  "1091": "V tom domu jest mnogo prostora.",
  "1092": "On boji se temoty.",
  "1093": "Pomsta jest sladka, ale opasna."
};
